imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es_ES

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

easy_admin:
    site_name: EcoMotoSoft
    design:
#        brand_color: 'rgba(26, 188, 156, 0.85)'
    entities:
#        Citas:
#            class: AppBundle\Entity\Citas
#        Clientes:
#            class: AppBundle\Entity\Clientes
        Codpostales:
            class: AppBundle\Entity\Codpostales
#        Dencomerciales:
#            class: AppBundle\Entity\Dencomerciales
#        Detfacturas1:
#            class: AppBundle\Entity\Detfacturas1
#        Detfacturas2:
#            class: AppBundle\Entity\Detfacturas2
#        Detordenestrabajo1:
#            class: AppBundle\Entity\Detordenestrabajo1
#        Detordenestrabajo2:
#            class: AppBundle\Entity\Detordenestrabajo2
#        Detpresupuestos1:
#            class: AppBundle\Entity\Detpresupuestos1
#        Detpresupuestos2:
#            class: AppBundle\Entity\Detpresupuestos2
#        Empleados:
#            class: AppBundle\Entity\Empleados
        Empresas:
            class: AppBundle\Entity\Empresas
            list:
                fields: [nifCif, nomfiscal, nomcomercial, direccion, activo, autorizado]
        Entbancarias:
            label: Entidades Bancarias
            class: AppBundle\Entity\Entbancarias
#        Entradasosalidas:
#            class: AppBundle\Entity\Entradasosalidas
#        Estados:
#            class: AppBundle\Entity\Estados
#        Fabricantes:
#            class: AppBundle\Entity\Fabricantes
#        Facturas:
#            class: AppBundle\Entity\Facturas
#        Familias:
#            class: AppBundle\Entity\Familias
        Idiomas:
            class: AppBundle\Entity\Idiomas
            list:
                fields: [idioma1]
#        Impuestos:
#            class: AppBundle\Entity\Impuestos
#        Ingresos:
#            class: AppBundle\Entity\Ingresos
#        Inventarios:
#            class: AppBundle\Entity\Inventarios
#        Marcas:
#            class: AppBundle\Entity\Marcas
#        Modelos:
#            class: AppBundle\Entity\Modelos
#        Monedas:
#            class: AppBundle\Entity\Monedas
#        Ordenestrabajo:
#            class: AppBundle\Entity\Ordenestrabajos
        Paises:
            class: AppBundle\Entity\Paises
            list:
                fields: [pais1, bandera]
#        Poblaciones:
#            class: AppBundle\Entity\Poblaciones
#        Presupuestos:
#            class: AppBundle\Entity\Presupuestos
#        Productos:
#            class: AppBundle\Entity\Productos
        Provincias:
            class: AppBundle\Entity\Provincias
            list:
                fields: [provincia1]
#        Servicios:
#            class: AppBundle\Entity\Servicios
#        Tipacciones:
#            class: AppBundle\Entity\Tipacciones
#        Tipclientes:
#            class: AppBundle\Entity\Tipclientes
#        Tipcombustibles:
#            class: AppBundle\Entity\Tipcombustibles
#        Tipcontactos:
#            class: AppBundle\Entity\Tipcontactos
#        Tipempleados:
#            class: AppBundle\Entity\Tipempleados
#        Tipingresos:
#            class: AppBundle\Entity\Tipingresos
#        Tippagos:
#            class: AppBundle\Entity\Tippagos
#        Tipvehiculos:
#            class: AppBundle\Entity\Tipvehiculos
#        Vehiculos:
#            class: AppBundle\Entity\Vehiculos
