app:
    resource: "@AppBundle/Controller/"
    type:     annotation

lemon_rest:
    resource: "@LemonRestBundle/Resources/config/routing.yml"
    prefix:   /api

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin