<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150615190428 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE citas DROP FOREIGN KEY citas_ibfk_1');
        $this->addSql('ALTER TABLE citas DROP FOREIGN KEY citas_ibfk_2');
        $this->addSql('ALTER TABLE citas DROP FOREIGN KEY citas_ibfk_3');
        $this->addSql('ALTER TABLE citas DROP FOREIGN KEY citas_ibfk_4');
        $this->addSql('ALTER TABLE citas CHANGE id_empresa id_empresa INT DEFAULT NULL, CHANGE id_cliente id_cliente INT DEFAULT NULL, CHANGE id_tipingreso id_tipingreso INT DEFAULT NULL, CHANGE id_vehiculo id_vehiculo INT DEFAULT NULL, CHANGE fechayhora fechayhora DATETIME NOT NULL');
        $this->addSql('ALTER TABLE citas ADD CONSTRAINT FK_B88CF8E59921FA96 FOREIGN KEY (id_vehiculo) REFERENCES vehiculos (id_vehiculo)');
        $this->addSql('ALTER TABLE citas ADD CONSTRAINT FK_B88CF8E5B4C5904D FOREIGN KEY (id_tipingreso) REFERENCES tipingresos (id_tipingreso)');
        $this->addSql('ALTER TABLE citas ADD CONSTRAINT FK_B88CF8E52A813255 FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente)');
        $this->addSql('ALTER TABLE citas ADD CONSTRAINT FK_B88CF8E5664AF320 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa)');
        $this->addSql('ALTER TABLE clientes DROP FOREIGN KEY clientes_ibfk_1');
        $this->addSql('ALTER TABLE clientes DROP FOREIGN KEY clientes_ibfk_2');
        $this->addSql('ALTER TABLE clientes DROP FOREIGN KEY clientes_ibfk_3');
        $this->addSql('ALTER TABLE clientes CHANGE id_tipcliente id_tipcliente INT DEFAULT NULL, CHANGE id_idioma id_idioma INT DEFAULT NULL, CHANGE id_codpostal id_codpostal INT DEFAULT NULL, CHANGE activo activo TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE clientes ADD CONSTRAINT FK_50FE07D777309A3F FOREIGN KEY (id_codpostal) REFERENCES codpostales (id_codpostal)');
        $this->addSql('ALTER TABLE clientes ADD CONSTRAINT FK_50FE07D73BFFEBE1 FOREIGN KEY (id_idioma) REFERENCES idiomas (id_idioma)');
        $this->addSql('ALTER TABLE clientes ADD CONSTRAINT FK_50FE07D78C422F77 FOREIGN KEY (id_tipcliente) REFERENCES tipclientes (id_tipcliente)');
        $this->addSql('ALTER TABLE codpostales DROP FOREIGN KEY codpostales_ibfk_1');
        $this->addSql('ALTER TABLE codpostales CHANGE id_poblacion id_poblacion INT DEFAULT NULL');
        $this->addSql('ALTER TABLE codpostales ADD CONSTRAINT FK_C049473A7EE3862E FOREIGN KEY (id_poblacion) REFERENCES poblaciones (id_poblacion)');
        $this->addSql('ALTER TABLE dencomerciales DROP FOREIGN KEY dencomerciales_ibfk_1');
        $this->addSql('ALTER TABLE dencomerciales CHANGE id_fabricante id_fabricante INT DEFAULT NULL');
        $this->addSql('ALTER TABLE dencomerciales ADD CONSTRAINT FK_38EC7CCA7EE963D3 FOREIGN KEY (id_fabricante) REFERENCES fabricantes (id_fabricante)');
        $this->addSql('ALTER TABLE detfacturas1 DROP FOREIGN KEY detfacturas1_ibfk_1');
        $this->addSql('ALTER TABLE detfacturas1 DROP FOREIGN KEY detfacturas1_ibfk_2');
        $this->addSql('ALTER TABLE detfacturas1 CHANGE id_factura id_factura INT DEFAULT NULL, CHANGE id_producto id_producto INT DEFAULT NULL');
        $this->addSql('ALTER TABLE detfacturas1 ADD CONSTRAINT FK_7BA84394F760EA80 FOREIGN KEY (id_producto) REFERENCES productos (id_producto)');
        $this->addSql('ALTER TABLE detfacturas1 ADD CONSTRAINT FK_7BA8439427760979 FOREIGN KEY (id_factura) REFERENCES facturas (id_factura)');
        $this->addSql('ALTER TABLE detfacturas2 DROP FOREIGN KEY detfacturas2_ibfk_1');
        $this->addSql('ALTER TABLE detfacturas2 DROP FOREIGN KEY detfacturas2_ibfk_2');
        $this->addSql('ALTER TABLE detfacturas2 CHANGE id_factura id_factura INT DEFAULT NULL, CHANGE id_servicio id_servicio INT DEFAULT NULL');
        $this->addSql('ALTER TABLE detfacturas2 ADD CONSTRAINT FK_E2A1122E9B5D1EBF FOREIGN KEY (id_servicio) REFERENCES servicios (id_servicio)');
        $this->addSql('ALTER TABLE detfacturas2 ADD CONSTRAINT FK_E2A1122E27760979 FOREIGN KEY (id_factura) REFERENCES facturas (id_factura)');
        $this->addSql('ALTER TABLE detordenestrabajos1 DROP FOREIGN KEY detordenestrabajos1_ibfk_1');
        $this->addSql('ALTER TABLE detordenestrabajos1 DROP FOREIGN KEY detordenestrabajos1_ibfk_2');
        $this->addSql('ALTER TABLE detordenestrabajos1 CHANGE id_ordentrabajo id_ordentrabajo INT DEFAULT NULL, CHANGE id_producto id_producto INT DEFAULT NULL');
        $this->addSql('ALTER TABLE detordenestrabajos1 ADD CONSTRAINT FK_E36A4F0EF760EA80 FOREIGN KEY (id_producto) REFERENCES productos (id_producto)');
        $this->addSql('ALTER TABLE detordenestrabajos1 ADD CONSTRAINT FK_E36A4F0ECFBF1E4A FOREIGN KEY (id_ordentrabajo) REFERENCES ordenestrabajos (id_ordentrabajo)');
        $this->addSql('ALTER TABLE detordenestrabajos2 DROP FOREIGN KEY detordenestrabajos2_ibfk_1');
        $this->addSql('ALTER TABLE detordenestrabajos2 DROP FOREIGN KEY detordenestrabajos2_ibfk_2');
        $this->addSql('ALTER TABLE detordenestrabajos2 CHANGE id_ordentrabajo id_ordentrabajo INT DEFAULT NULL, CHANGE id_servicio id_servicio INT DEFAULT NULL');
        $this->addSql('ALTER TABLE detordenestrabajos2 ADD CONSTRAINT FK_7A631EB49B5D1EBF FOREIGN KEY (id_servicio) REFERENCES servicios (id_servicio)');
        $this->addSql('ALTER TABLE detordenestrabajos2 ADD CONSTRAINT FK_7A631EB4CFBF1E4A FOREIGN KEY (id_ordentrabajo) REFERENCES ordenestrabajos (id_ordentrabajo)');
        $this->addSql('ALTER TABLE detpresupuestos1 DROP FOREIGN KEY detpresupuestos1_ibfk_1');
        $this->addSql('ALTER TABLE detpresupuestos1 DROP FOREIGN KEY detpresupuestos1_ibfk_2');
        $this->addSql('ALTER TABLE detpresupuestos1 CHANGE id_presupuesto id_presupuesto INT DEFAULT NULL, CHANGE id_producto id_producto INT DEFAULT NULL');
        $this->addSql('ALTER TABLE detpresupuestos1 ADD CONSTRAINT FK_71AC57C4F760EA80 FOREIGN KEY (id_producto) REFERENCES productos (id_producto)');
        $this->addSql('ALTER TABLE detpresupuestos1 ADD CONSTRAINT FK_71AC57C4371A524 FOREIGN KEY (id_presupuesto) REFERENCES presupuestos (id_presupuesto)');
        $this->addSql('ALTER TABLE detpresupuestos2 DROP FOREIGN KEY detpresupuestos2_ibfk_1');
        $this->addSql('ALTER TABLE detpresupuestos2 DROP FOREIGN KEY detpresupuestos2_ibfk_2');
        $this->addSql('ALTER TABLE detpresupuestos2 CHANGE id_presupuesto id_presupuesto INT DEFAULT NULL, CHANGE id_servicio id_servicio INT DEFAULT NULL');
        $this->addSql('ALTER TABLE detpresupuestos2 ADD CONSTRAINT FK_E8A5067E9B5D1EBF FOREIGN KEY (id_servicio) REFERENCES servicios (id_servicio)');
        $this->addSql('ALTER TABLE detpresupuestos2 ADD CONSTRAINT FK_E8A5067E371A524 FOREIGN KEY (id_presupuesto) REFERENCES presupuestos (id_presupuesto)');
        $this->addSql('ALTER TABLE empleados DROP FOREIGN KEY empleados_ibfk_1');
        $this->addSql('ALTER TABLE empleados DROP FOREIGN KEY empleados_ibfk_2');
        $this->addSql('ALTER TABLE empleados DROP FOREIGN KEY empleados_ibfk_3');
        $this->addSql('ALTER TABLE empleados CHANGE id_tipempleado id_tipempleado INT DEFAULT NULL, CHANGE id_idioma id_idioma INT DEFAULT NULL, CHANGE id_codpostal id_codpostal INT DEFAULT NULL, CHANGE activo activo TINYINT(1) DEFAULT NULL, CHANGE autorizado autorizado TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE empleados ADD CONSTRAINT FK_9EB2266C77309A3F FOREIGN KEY (id_codpostal) REFERENCES codpostales (id_codpostal)');
        $this->addSql('ALTER TABLE empleados ADD CONSTRAINT FK_9EB2266C3BFFEBE1 FOREIGN KEY (id_idioma) REFERENCES idiomas (id_idioma)');
        $this->addSql('ALTER TABLE empleados ADD CONSTRAINT FK_9EB2266C5CC4D13E FOREIGN KEY (id_tipempleado) REFERENCES tipempleados (id_tipempleado)');
        $this->addSql('ALTER TABLE empresas DROP FOREIGN KEY empresas_ibfk_1');
        $this->addSql('ALTER TABLE empresas DROP FOREIGN KEY empresas_ibfk_2');
        $this->addSql('ALTER TABLE empresas CHANGE id_idioma id_idioma INT DEFAULT NULL, CHANGE id_codpostal id_codpostal INT DEFAULT NULL, CHANGE activo activo TINYINT(1) DEFAULT NULL, CHANGE autorizado autorizado TINYINT(1) DEFAULT NULL, CHANGE proveedor proveedor TINYINT(1) DEFAULT NULL, CHANGE concesionario concesionario TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE empresas ADD CONSTRAINT FK_70DD49A577309A3F FOREIGN KEY (id_codpostal) REFERENCES codpostales (id_codpostal)');
        $this->addSql('ALTER TABLE empresas ADD CONSTRAINT FK_70DD49A53BFFEBE1 FOREIGN KEY (id_idioma) REFERENCES idiomas (id_idioma)');
        $this->addSql('ALTER TABLE entradasosalidas DROP FOREIGN KEY entradasosalidas_ibfk_1');
        $this->addSql('ALTER TABLE entradasosalidas DROP FOREIGN KEY entradasosalidas_ibfk_2');
        $this->addSql('ALTER TABLE entradasosalidas CHANGE id_empresa id_empresa INT DEFAULT NULL, CHANGE id_producto id_producto INT DEFAULT NULL, CHANGE fecentradaosalida fecentradaosalida DATETIME NOT NULL');
        $this->addSql('ALTER TABLE entradasosalidas ADD CONSTRAINT FK_7A4F7947F760EA80 FOREIGN KEY (id_producto) REFERENCES productos (id_producto)');
        $this->addSql('ALTER TABLE entradasosalidas ADD CONSTRAINT FK_7A4F7947664AF320 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa)');
        $this->addSql('ALTER TABLE estados CHANGE estado_1 estado_1 VARCHAR(20) NOT NULL, CHANGE estado_2 estado_2 VARCHAR(30) DEFAULT NULL, CHANGE estado_3 estado_3 VARCHAR(30) DEFAULT NULL, CHANGE estado_4 estado_4 VARCHAR(30) DEFAULT NULL, CHANGE estado_5 estado_5 VARCHAR(30) DEFAULT NULL, CHANGE estado_6 estado_6 VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE facturas DROP FOREIGN KEY facturas_ibfk_1');
        $this->addSql('ALTER TABLE facturas DROP FOREIGN KEY facturas_ibfk_2');
        $this->addSql('ALTER TABLE facturas DROP FOREIGN KEY facturas_ibfk_3');
        $this->addSql('ALTER TABLE facturas DROP FOREIGN KEY facturas_ibfk_4');
        $this->addSql('ALTER TABLE facturas DROP FOREIGN KEY facturas_ibfk_5');
        $this->addSql('ALTER TABLE facturas DROP FOREIGN KEY facturas_ibfk_6');
        $this->addSql('ALTER TABLE facturas DROP FOREIGN KEY facturas_ibfk_7');
        $this->addSql('ALTER TABLE facturas CHANGE id_empresa id_empresa INT DEFAULT NULL, CHANGE id_presupuesto id_presupuesto INT DEFAULT NULL, CHANGE id_ingreso id_ingreso INT DEFAULT NULL, CHANGE id_tipaccion id_tipaccion INT DEFAULT NULL, CHANGE id_cliente id_cliente INT DEFAULT NULL, CHANGE id_tippago id_tippago INT DEFAULT NULL, CHANGE id_ordentrabajo id_ordentrabajo INT DEFAULT NULL, CHANGE fecha fecha DATETIME NOT NULL');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT FK_622B9C0F5864BC49 FOREIGN KEY (id_tippago) REFERENCES tippagos (id_tippago)');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT FK_622B9C0FCFBF1E4A FOREIGN KEY (id_ordentrabajo) REFERENCES ordenestrabajos (id_ordentrabajo)');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT FK_622B9C0F2A813255 FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente)');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT FK_622B9C0FD37F13FC FOREIGN KEY (id_tipaccion) REFERENCES tipacciones (id_tipaccion)');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT FK_622B9C0F371A524 FOREIGN KEY (id_presupuesto) REFERENCES presupuestos (id_presupuesto)');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT FK_622B9C0F12068D6F FOREIGN KEY (id_ingreso) REFERENCES ingresos (id_ingreso)');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT FK_622B9C0F664AF320 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa)');
        $this->addSql('ALTER TABLE familias CHANGE familia_1 familia_1 VARCHAR(40) NOT NULL, CHANGE familia_2 familia_2 VARCHAR(40) DEFAULT NULL, CHANGE familia_3 familia_3 VARCHAR(40) DEFAULT NULL, CHANGE familia_4 familia_4 VARCHAR(40) DEFAULT NULL, CHANGE familia_5 familia_5 VARCHAR(40) DEFAULT NULL, CHANGE familia_6 familia_6 VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE idiomas DROP FOREIGN KEY idiomas_ibfk_1');
        $this->addSql('ALTER TABLE idiomas CHANGE id_pais id_pais INT DEFAULT NULL, CHANGE idioma_1 idioma_1 VARCHAR(30) NOT NULL, CHANGE idioma_2 idioma_2 VARCHAR(30) DEFAULT NULL, CHANGE idioma_3 idioma_3 VARCHAR(30) DEFAULT NULL, CHANGE idioma_4 idioma_4 VARCHAR(30) DEFAULT NULL, CHANGE idioma_5 idioma_5 VARCHAR(30) DEFAULT NULL, CHANGE idioma_6 idioma_6 VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE idiomas ADD CONSTRAINT FK_12A54B7EF57D32FD FOREIGN KEY (id_pais) REFERENCES paises (id_pais)');
        $this->addSql('ALTER TABLE ingresos DROP FOREIGN KEY ingresos_ibfk_1');
        $this->addSql('ALTER TABLE ingresos DROP FOREIGN KEY ingresos_ibfk_2');
        $this->addSql('ALTER TABLE ingresos DROP FOREIGN KEY ingresos_ibfk_3');
        $this->addSql('ALTER TABLE ingresos DROP FOREIGN KEY ingresos_ibfk_4');
        $this->addSql('ALTER TABLE ingresos DROP FOREIGN KEY ingresos_ibfk_5');
        $this->addSql('ALTER TABLE ingresos CHANGE id_empresa id_empresa INT DEFAULT NULL, CHANGE id_cliente id_cliente INT DEFAULT NULL, CHANGE id_vehiculo id_vehiculo INT DEFAULT NULL, CHANGE id_estado id_estado INT DEFAULT NULL, CHANGE id_tipingreso id_tipingreso INT DEFAULT NULL, CHANGE fyhingreso fyhingreso DATETIME NOT NULL, CHANGE fyhinicio fyhinicio DATETIME NOT NULL, CHANGE fyhfinalizacion fyhfinalizacion DATETIME NOT NULL, CHANGE fyhentrega fyhentrega DATETIME NOT NULL');
        $this->addSql('ALTER TABLE ingresos ADD CONSTRAINT FK_96CA59DAB4C5904D FOREIGN KEY (id_tipingreso) REFERENCES tipingresos (id_tipingreso)');
        $this->addSql('ALTER TABLE ingresos ADD CONSTRAINT FK_96CA59DA6A540E FOREIGN KEY (id_estado) REFERENCES estados (id_estado)');
        $this->addSql('ALTER TABLE ingresos ADD CONSTRAINT FK_96CA59DA9921FA96 FOREIGN KEY (id_vehiculo) REFERENCES vehiculos (id_vehiculo)');
        $this->addSql('ALTER TABLE ingresos ADD CONSTRAINT FK_96CA59DA2A813255 FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente)');
        $this->addSql('ALTER TABLE ingresos ADD CONSTRAINT FK_96CA59DA664AF320 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa)');
        $this->addSql('ALTER TABLE inventarios DROP FOREIGN KEY inventarios_ibfk_1');
        $this->addSql('ALTER TABLE inventarios DROP FOREIGN KEY inventarios_ibfk_2');
        $this->addSql('ALTER TABLE inventarios ADD CONSTRAINT FK_D6B3D0D6F760EA80 FOREIGN KEY (id_producto) REFERENCES productos (id_producto)');
        $this->addSql('ALTER TABLE inventarios ADD CONSTRAINT FK_D6B3D0D6664AF320 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa)');
        $this->addSql('ALTER TABLE modelos DROP FOREIGN KEY modelos_ibfk_1');
        $this->addSql('ALTER TABLE modelos DROP FOREIGN KEY modelos_ibfk_2');
        $this->addSql('ALTER TABLE modelos DROP FOREIGN KEY modelos_ibfk_3');
        $this->addSql('ALTER TABLE modelos DROP FOREIGN KEY modelos_ibfk_4');
        $this->addSql('ALTER TABLE modelos CHANGE id_dencomercial id_dencomercial INT DEFAULT NULL, CHANGE id_tipvehiculo id_tipvehiculo INT DEFAULT NULL, CHANGE id_fabricante id_fabricante INT DEFAULT NULL, CHANGE id_tipcombustible id_tipcombustible INT DEFAULT NULL');
        $this->addSql('ALTER TABLE modelos ADD CONSTRAINT FK_8441FCC2A253177B FOREIGN KEY (id_tipcombustible) REFERENCES tipcombustibles (id_tipcombustible)');
        $this->addSql('ALTER TABLE modelos ADD CONSTRAINT FK_8441FCC27EE963D3 FOREIGN KEY (id_fabricante) REFERENCES fabricantes (id_fabricante)');
        $this->addSql('ALTER TABLE modelos ADD CONSTRAINT FK_8441FCC24CE7786F FOREIGN KEY (id_tipvehiculo) REFERENCES tipvehiculos (id_tipvehiculo)');
        $this->addSql('ALTER TABLE modelos ADD CONSTRAINT FK_8441FCC296F53A11 FOREIGN KEY (id_dencomercial) REFERENCES dencomerciales (id_dencomercial)');
        $this->addSql('ALTER TABLE monedas CHANGE moneda_1 moneda_1 VARCHAR(30) NOT NULL, CHANGE moneda_2 moneda_2 VARCHAR(30) DEFAULT NULL, CHANGE moneda_3 moneda_3 VARCHAR(30) DEFAULT NULL, CHANGE moneda_4 moneda_4 VARCHAR(30) DEFAULT NULL, CHANGE moneda_5 moneda_5 VARCHAR(30) DEFAULT NULL, CHANGE moneda_6 moneda_6 VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE ordenestrabajos DROP FOREIGN KEY ordenestrabajos_ibfk_1');
        $this->addSql('ALTER TABLE ordenestrabajos DROP FOREIGN KEY ordenestrabajos_ibfk_2');
        $this->addSql('ALTER TABLE ordenestrabajos DROP FOREIGN KEY ordenestrabajos_ibfk_3');
        $this->addSql('ALTER TABLE ordenestrabajos CHANGE id_empresa id_empresa INT DEFAULT NULL, CHANGE id_empleado id_empleado INT DEFAULT NULL, CHANGE id_ingreso id_ingreso INT DEFAULT NULL, CHANGE fecha fecha DATETIME NOT NULL, CHANGE presupuestado presupuestado TINYINT(1) DEFAULT NULL, CHANGE facturado facturado TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE ordenestrabajos ADD CONSTRAINT FK_D699FB7F12068D6F FOREIGN KEY (id_ingreso) REFERENCES ingresos (id_ingreso)');
        $this->addSql('ALTER TABLE ordenestrabajos ADD CONSTRAINT FK_D699FB7F890253C7 FOREIGN KEY (id_empleado) REFERENCES empleados (id_empleado)');
        $this->addSql('ALTER TABLE ordenestrabajos ADD CONSTRAINT FK_D699FB7F664AF320 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa)');
        $this->addSql('ALTER TABLE paises DROP FOREIGN KEY paises_ibfk_1');
        $this->addSql('ALTER TABLE paises DROP FOREIGN KEY paises_ibfk_2');
        $this->addSql('ALTER TABLE paises CHANGE id_moneda id_moneda INT DEFAULT NULL, CHANGE id_impuesto id_impuesto INT DEFAULT NULL, CHANGE pais_1 pais_1 VARCHAR(50) NOT NULL, CHANGE pais_2 pais_2 VARCHAR(50) DEFAULT NULL, CHANGE pais_3 pais_3 VARCHAR(50) DEFAULT NULL, CHANGE pais_4 pais_4 VARCHAR(50) DEFAULT NULL, CHANGE pais_5 pais_5 VARCHAR(50) DEFAULT NULL, CHANGE pais_6 pais_6 VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE paises ADD CONSTRAINT FK_DFAD237BE63DD634 FOREIGN KEY (id_impuesto) REFERENCES impuestos (id_impuesto)');
        $this->addSql('ALTER TABLE paises ADD CONSTRAINT FK_DFAD237B963C9EC0 FOREIGN KEY (id_moneda) REFERENCES monedas (id_moneda)');
        $this->addSql('ALTER TABLE poblaciones DROP FOREIGN KEY poblaciones_ibfk_1');
        $this->addSql('ALTER TABLE poblaciones CHANGE id_provincia id_provincia INT DEFAULT NULL, CHANGE poblacion_1 poblacion_1 VARCHAR(50) NOT NULL, CHANGE poblacion_2 poblacion_2 VARCHAR(50) NOT NULL, CHANGE poblacion_3 poblacion_3 VARCHAR(50) NOT NULL, CHANGE poblacion_4 poblacion_4 VARCHAR(50) NOT NULL, CHANGE poblacion_5 poblacion_5 VARCHAR(50) NOT NULL, CHANGE poblacion_6 poblacion_6 VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE poblaciones ADD CONSTRAINT FK_879131B653AF4E34 FOREIGN KEY (id_provincia) REFERENCES provincias (id_provincia)');
        $this->addSql('ALTER TABLE presupuestos DROP FOREIGN KEY presupuestos_ibfk_1');
        $this->addSql('ALTER TABLE presupuestos DROP FOREIGN KEY presupuestos_ibfk_2');
        $this->addSql('ALTER TABLE presupuestos DROP FOREIGN KEY presupuestos_ibfk_3');
        $this->addSql('ALTER TABLE presupuestos DROP FOREIGN KEY presupuestos_ibfk_4');
        $this->addSql('ALTER TABLE presupuestos DROP FOREIGN KEY presupuestos_ibfk_5');
        $this->addSql('ALTER TABLE presupuestos CHANGE id_empresa id_empresa INT DEFAULT NULL, CHANGE id_ingreso id_ingreso INT DEFAULT NULL, CHANGE id_tipaccion id_tipaccion INT DEFAULT NULL, CHANGE id_cliente id_cliente INT DEFAULT NULL, CHANGE id_ordentrabajo id_ordentrabajo INT DEFAULT NULL, CHANGE fecha fecha DATETIME NOT NULL, CHANGE avisado avisado TINYINT(1) DEFAULT NULL, CHANGE facturado facturado TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE presupuestos ADD CONSTRAINT FK_4CF2F0DCFBF1E4A FOREIGN KEY (id_ordentrabajo) REFERENCES ordenestrabajos (id_ordentrabajo)');
        $this->addSql('ALTER TABLE presupuestos ADD CONSTRAINT FK_4CF2F0D2A813255 FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente)');
        $this->addSql('ALTER TABLE presupuestos ADD CONSTRAINT FK_4CF2F0DD37F13FC FOREIGN KEY (id_tipaccion) REFERENCES tipacciones (id_tipaccion)');
        $this->addSql('ALTER TABLE presupuestos ADD CONSTRAINT FK_4CF2F0D12068D6F FOREIGN KEY (id_ingreso) REFERENCES ingresos (id_ingreso)');
        $this->addSql('ALTER TABLE presupuestos ADD CONSTRAINT FK_4CF2F0D664AF320 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa)');
        $this->addSql('ALTER TABLE productos DROP FOREIGN KEY productos_ibfk_1');
        $this->addSql('ALTER TABLE productos DROP FOREIGN KEY productos_ibfk_2');
        $this->addSql('ALTER TABLE productos CHANGE id_marca id_marca INT DEFAULT NULL, CHANGE id_familia id_familia INT DEFAULT NULL, CHANGE descripcion_1 descripcion_1 VARCHAR(50) NOT NULL, CHANGE descripcion_2 descripcion_2 VARCHAR(50) DEFAULT NULL, CHANGE descripcion_3 descripcion_3 VARCHAR(50) DEFAULT NULL, CHANGE descripcion_4 descripcion_4 VARCHAR(50) DEFAULT NULL, CHANGE descripcion_5 descripcion_5 VARCHAR(50) DEFAULT NULL, CHANGE descripcion_6 descripcion_6 VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE productos ADD CONSTRAINT FK_767490E680F46B3F FOREIGN KEY (id_familia) REFERENCES familias (id_familia)');
        $this->addSql('ALTER TABLE productos ADD CONSTRAINT FK_767490E6E98F4023 FOREIGN KEY (id_marca) REFERENCES marcas (id_marca)');
        $this->addSql('ALTER TABLE provincias DROP FOREIGN KEY provincias_ibfk_1');
        $this->addSql('ALTER TABLE provincias CHANGE id_pais id_pais INT DEFAULT NULL, CHANGE provincia_1 provincia_1 VARCHAR(50) NOT NULL, CHANGE provincia_2 provincia_2 VARCHAR(30) DEFAULT NULL, CHANGE provincia_3 provincia_3 VARCHAR(30) DEFAULT NULL, CHANGE provincia_4 provincia_4 VARCHAR(30) DEFAULT NULL, CHANGE provincia_5 provincia_5 VARCHAR(30) DEFAULT NULL, CHANGE provincia_6 provincia_6 VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE provincias ADD CONSTRAINT FK_9F631427F57D32FD FOREIGN KEY (id_pais) REFERENCES paises (id_pais)');
        $this->addSql('ALTER TABLE relempresasclientes DROP FOREIGN KEY relempresasclientes_ibfk_1');
        $this->addSql('ALTER TABLE relempresasclientes DROP FOREIGN KEY relempresasclientes_ibfk_2');
        $this->addSql('ALTER TABLE relempresasclientes CHANGE id_empresa id_empresa INT DEFAULT NULL, CHANGE id_cliente id_cliente INT DEFAULT NULL, CHANGE fecalta fecalta DATETIME NOT NULL');
        $this->addSql('ALTER TABLE relempresasclientes ADD CONSTRAINT FK_EBB782BE2A813255 FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente)');
        $this->addSql('ALTER TABLE relempresasclientes ADD CONSTRAINT FK_EBB782BE664AF320 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa)');
        $this->addSql('ALTER TABLE relempresascuecorrientes DROP FOREIGN KEY relempresascuecorrientes_ibfk_1');
        $this->addSql('ALTER TABLE relempresascuecorrientes DROP FOREIGN KEY relempresascuecorrientes_ibfk_2');
        $this->addSql('ALTER TABLE relempresascuecorrientes CHANGE id_empresa id_empresa INT DEFAULT NULL, CHANGE id_entbancaria id_entbancaria INT DEFAULT NULL');
        $this->addSql('ALTER TABLE relempresascuecorrientes ADD CONSTRAINT FK_1CDE511B3971CE23 FOREIGN KEY (id_entbancaria) REFERENCES entbancarias (id_entbancaria)');
        $this->addSql('ALTER TABLE relempresascuecorrientes ADD CONSTRAINT FK_1CDE511B664AF320 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa)');
        $this->addSql('ALTER TABLE relempresasemails DROP FOREIGN KEY relempresasemails_ibfk_1');
        $this->addSql('ALTER TABLE relempresasemails DROP FOREIGN KEY relempresasemails_ibfk_2');
        $this->addSql('ALTER TABLE relempresasemails CHANGE id_empresa id_empresa INT DEFAULT NULL, CHANGE id_tipcontacto id_tipcontacto INT DEFAULT NULL');
        $this->addSql('ALTER TABLE relempresasemails ADD CONSTRAINT FK_3C73317BA25C2750 FOREIGN KEY (id_tipcontacto) REFERENCES tipcontactos (id_tipcontacto)');
        $this->addSql('ALTER TABLE relempresasemails ADD CONSTRAINT FK_3C73317B664AF320 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa)');
        $this->addSql('ALTER TABLE relempresasempleados DROP FOREIGN KEY relempresasempleados_ibfk_1');
        $this->addSql('ALTER TABLE relempresasempleados DROP FOREIGN KEY relempresasempleados_ibfk_2');
        $this->addSql('ALTER TABLE relempresasempleados CHANGE id_empresa id_empresa INT DEFAULT NULL, CHANGE id_empleado id_empleado INT DEFAULT NULL, CHANGE fecalta fecalta DATETIME NOT NULL, CHANGE despedido despedido TINYINT(1) DEFAULT NULL, CHANGE fecbaja fecbaja DATETIME NOT NULL');
        $this->addSql('ALTER TABLE relempresasempleados ADD CONSTRAINT FK_AA67B615890253C7 FOREIGN KEY (id_empleado) REFERENCES empleados (id_empleado)');
        $this->addSql('ALTER TABLE relempresasempleados ADD CONSTRAINT FK_AA67B615664AF320 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa)');
        $this->addSql('ALTER TABLE relempresasfabricantes DROP FOREIGN KEY relempresasfabricantes_ibfk_1');
        $this->addSql('ALTER TABLE relempresasfabricantes DROP FOREIGN KEY relempresasfabricantes_ibfk_2');
        $this->addSql('ALTER TABLE relempresasfabricantes CHANGE id_empresa id_empresa INT DEFAULT NULL, CHANGE id_fabricante id_fabricante INT DEFAULT NULL');
        $this->addSql('ALTER TABLE relempresasfabricantes ADD CONSTRAINT FK_124A0DDF7EE963D3 FOREIGN KEY (id_fabricante) REFERENCES fabricantes (id_fabricante)');
        $this->addSql('ALTER TABLE relempresasfabricantes ADD CONSTRAINT FK_124A0DDF664AF320 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa)');
        $this->addSql('ALTER TABLE relempresasroductos DROP FOREIGN KEY relempresasroductos_ibfk_1');
        $this->addSql('ALTER TABLE relempresasroductos DROP FOREIGN KEY relempresasroductos_ibfk_2');
        $this->addSql('ALTER TABLE relempresasroductos CHANGE id_empresa id_empresa INT DEFAULT NULL, CHANGE id_producto id_producto INT DEFAULT NULL');
        $this->addSql('ALTER TABLE relempresasroductos ADD CONSTRAINT FK_BEB51D9DF760EA80 FOREIGN KEY (id_producto) REFERENCES productos (id_producto)');
        $this->addSql('ALTER TABLE relempresasroductos ADD CONSTRAINT FK_BEB51D9D664AF320 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa)');
        $this->addSql('ALTER TABLE relempresasservicios DROP FOREIGN KEY relempresasservicios_ibfk_1');
        $this->addSql('ALTER TABLE relempresasservicios DROP FOREIGN KEY relempresasservicios_ibfk_2');
        $this->addSql('ALTER TABLE relempresasservicios CHANGE id_empresa id_empresa INT DEFAULT NULL, CHANGE id_servicio id_servicio INT DEFAULT NULL');
        $this->addSql('ALTER TABLE relempresasservicios ADD CONSTRAINT FK_F4AB10569B5D1EBF FOREIGN KEY (id_servicio) REFERENCES servicios (id_servicio)');
        $this->addSql('ALTER TABLE relempresasservicios ADD CONSTRAINT FK_F4AB1056664AF320 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa)');
        $this->addSql('ALTER TABLE relempresastelefonos DROP FOREIGN KEY relempresastelefonos_ibfk_1');
        $this->addSql('ALTER TABLE relempresastelefonos DROP FOREIGN KEY relempresastelefonos_ibfk_2');
        $this->addSql('ALTER TABLE relempresastelefonos CHANGE id_empresa id_empresa INT DEFAULT NULL, CHANGE id_tipcontacto id_tipcontacto INT DEFAULT NULL');
        $this->addSql('ALTER TABLE relempresastelefonos ADD CONSTRAINT FK_EFA0D4D5A25C2750 FOREIGN KEY (id_tipcontacto) REFERENCES tipcontactos (id_tipcontacto)');
        $this->addSql('ALTER TABLE relempresastelefonos ADD CONSTRAINT FK_EFA0D4D5664AF320 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa)');
        $this->addSql('ALTER TABLE relmodelosproductos DROP FOREIGN KEY relmodelosproductos_ibfk_1');
        $this->addSql('ALTER TABLE relmodelosproductos DROP FOREIGN KEY relmodelosproductos_ibfk_2');
        $this->addSql('ALTER TABLE relmodelosproductos CHANGE id_modelo id_modelo INT DEFAULT NULL, CHANGE id_producto id_producto INT DEFAULT NULL');
        $this->addSql('ALTER TABLE relmodelosproductos ADD CONSTRAINT FK_F0D9213BF760EA80 FOREIGN KEY (id_producto) REFERENCES productos (id_producto)');
        $this->addSql('ALTER TABLE relmodelosproductos ADD CONSTRAINT FK_F0D9213BD6E0D9AB FOREIGN KEY (id_modelo) REFERENCES modelos (id_modelo)');
        $this->addSql('ALTER TABLE relmodelosservicios DROP FOREIGN KEY relmodelosservicios_ibfk_1');
        $this->addSql('ALTER TABLE relmodelosservicios DROP FOREIGN KEY relmodelosservicios_ibfk_2');
        $this->addSql('ALTER TABLE relmodelosservicios CHANGE id_modelo id_modelo INT DEFAULT NULL, CHANGE id_servicio id_servicio INT DEFAULT NULL');
        $this->addSql('ALTER TABLE relmodelosservicios ADD CONSTRAINT FK_46D331F29B5D1EBF FOREIGN KEY (id_servicio) REFERENCES servicios (id_servicio)');
        $this->addSql('ALTER TABLE relmodelosservicios ADD CONSTRAINT FK_46D331F2D6E0D9AB FOREIGN KEY (id_modelo) REFERENCES modelos (id_modelo)');
        $this->addSql('ALTER TABLE relproductosproductos DROP FOREIGN KEY relproductosproductos_ibfk_1');
        $this->addSql('ALTER TABLE relproductosproductos DROP FOREIGN KEY relproductosproductos_ibfk_2');
        $this->addSql('ALTER TABLE relproductosproductos CHANGE id_producto1 id_producto1 INT DEFAULT NULL, CHANGE id_producto2 id_producto2 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE relproductosproductos ADD CONSTRAINT FK_B0591DB5F79A5DC7 FOREIGN KEY (id_producto2) REFERENCES productos (id_producto)');
        $this->addSql('ALTER TABLE relproductosproductos ADD CONSTRAINT FK_B0591DB56E930C7D FOREIGN KEY (id_producto1) REFERENCES productos (id_producto)');
        $this->addSql('ALTER TABLE servicios CHANGE servicio_1 servicio_1 VARCHAR(50) NOT NULL, CHANGE servicio_2 servicio_2 VARCHAR(50) DEFAULT NULL, CHANGE servicio_3 servicio_3 VARCHAR(50) DEFAULT NULL, CHANGE servicio_4 servicio_4 VARCHAR(50) DEFAULT NULL, CHANGE servicio_5 servicio_5 VARCHAR(50) DEFAULT NULL, CHANGE servicio_6 servicio_6 VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE tipacciones CHANGE tipaccion_1 tipaccion_1 VARCHAR(20) NOT NULL, CHANGE tipaccion_2 tipaccion_2 VARCHAR(20) DEFAULT NULL, CHANGE tipaccion_3 tipaccion_3 VARCHAR(20) DEFAULT NULL, CHANGE tipaccion_4 tipaccion_4 VARCHAR(20) DEFAULT NULL, CHANGE tipaccion_5 tipaccion_5 VARCHAR(20) DEFAULT NULL, CHANGE tipaccion_6 tipaccion_6 VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE tipclientes CHANGE tipcliente_1 tipcliente_1 VARCHAR(20) NOT NULL, CHANGE tipcliente_2 tipcliente_2 VARCHAR(20) DEFAULT NULL, CHANGE tipcliente_3 tipcliente_3 VARCHAR(20) DEFAULT NULL, CHANGE tipcliente_4 tipcliente_4 VARCHAR(20) DEFAULT NULL, CHANGE tipcliente_5 tipcliente_5 VARCHAR(20) DEFAULT NULL, CHANGE tipcliente_6 tipcliente_6 VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE tipcombustibles CHANGE tipcombustible_1 tipcombustible_1 VARCHAR(20) NOT NULL, CHANGE tipcombustible_2 tipcombustible_2 VARCHAR(20) DEFAULT NULL, CHANGE tipcombustible_3 tipcombustible_3 VARCHAR(20) DEFAULT NULL, CHANGE tipcombustible_4 tipcombustible_4 VARCHAR(20) DEFAULT NULL, CHANGE tipcombustible_5 tipcombustible_5 VARCHAR(20) DEFAULT NULL, CHANGE tipcombustible_6 tipcombustible_6 VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE tipcontactos CHANGE tipcontacto_1 tipcontacto_1 VARCHAR(20) NOT NULL, CHANGE tipcontacto_2 tipcontacto_2 VARCHAR(20) DEFAULT NULL, CHANGE tipcontacto_3 tipcontacto_3 VARCHAR(20) DEFAULT NULL, CHANGE tipcontacto_4 tipcontacto_4 VARCHAR(20) DEFAULT NULL, CHANGE tipcontacto_5 tipcontacto_5 VARCHAR(20) DEFAULT NULL, CHANGE tipcontacto_6 tipcontacto_6 VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE tipempleados CHANGE tipempleado_1 tipempleado_1 VARCHAR(20) NOT NULL, CHANGE tipempleado_2 tipempleado_2 VARCHAR(20) DEFAULT NULL, CHANGE tipempleado_3 tipempleado_3 VARCHAR(20) DEFAULT NULL, CHANGE tipempleado_4 tipempleado_4 VARCHAR(20) DEFAULT NULL, CHANGE tipempleado_5 tipempleado_5 VARCHAR(20) DEFAULT NULL, CHANGE tipempleado_6 tipempleado_6 VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE tipingresos CHANGE tipingreso_1 tipingreso_1 VARCHAR(20) NOT NULL, CHANGE tipingreso_2 tipingreso_2 VARCHAR(20) DEFAULT NULL, CHANGE tipingreso_3 tipingreso_3 VARCHAR(20) DEFAULT NULL, CHANGE tipingreso_4 tipingreso_4 VARCHAR(20) DEFAULT NULL, CHANGE tipingreso_5 tipingreso_5 VARCHAR(20) DEFAULT NULL, CHANGE tipingreso_6 tipingreso_6 VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE tippagos CHANGE tippago_1 tippago_1 VARCHAR(30) NOT NULL, CHANGE tippago_2 tippago_2 VARCHAR(30) DEFAULT NULL, CHANGE tippago_3 tippago_3 VARCHAR(30) DEFAULT NULL, CHANGE tippago_4 tippago_4 VARCHAR(30) DEFAULT NULL, CHANGE tippago_5 tippago_5 VARCHAR(30) DEFAULT NULL, CHANGE tippago_6 tippago_6 VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE tipvehiculos CHANGE tipvehiculo_1 tipvehiculo_1 VARCHAR(20) NOT NULL, CHANGE tipvehiculo_2 tipvehiculo_2 VARCHAR(20) DEFAULT NULL, CHANGE tipvehiculo_3 tipvehiculo_3 VARCHAR(20) DEFAULT NULL, CHANGE tipvehiculo_4 tipvehiculo_4 VARCHAR(20) DEFAULT NULL, CHANGE tipvehiculo_5 tipvehiculo_5 VARCHAR(20) DEFAULT NULL, CHANGE tipvehiculo_6 tipvehiculo_6 VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE vehiculos DROP FOREIGN KEY vehiculos_ibfk_1');
        $this->addSql('ALTER TABLE vehiculos DROP FOREIGN KEY vehiculos_ibfk_2');
        $this->addSql('ALTER TABLE vehiculos DROP FOREIGN KEY vehiculos_ibfk_3');
        $this->addSql('ALTER TABLE vehiculos CHANGE id_pais id_pais INT DEFAULT NULL, CHANGE id_cliente id_cliente INT DEFAULT NULL, CHANGE id_modelo id_modelo INT DEFAULT NULL, CHANGE fecmatriculacion fecmatriculacion DATETIME NOT NULL, CHANGE fecfabricacion fecfabricacion DATETIME NOT NULL, CHANGE fecitv fecitv DATETIME NOT NULL, CHANGE fecmantenimiento fecmantenimiento DATETIME NOT NULL');
        $this->addSql('ALTER TABLE vehiculos ADD CONSTRAINT FK_82CE64A7D6E0D9AB FOREIGN KEY (id_modelo) REFERENCES modelos (id_modelo)');
        $this->addSql('ALTER TABLE vehiculos ADD CONSTRAINT FK_82CE64A72A813255 FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente)');
        $this->addSql('ALTER TABLE vehiculos ADD CONSTRAINT FK_82CE64A7F57D32FD FOREIGN KEY (id_pais) REFERENCES paises (id_pais)');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE citas DROP FOREIGN KEY FK_B88CF8E59921FA96');
        $this->addSql('ALTER TABLE citas DROP FOREIGN KEY FK_B88CF8E5B4C5904D');
        $this->addSql('ALTER TABLE citas DROP FOREIGN KEY FK_B88CF8E52A813255');
        $this->addSql('ALTER TABLE citas DROP FOREIGN KEY FK_B88CF8E5664AF320');
        $this->addSql('ALTER TABLE citas CHANGE id_cliente id_cliente INT NOT NULL COMMENT \'Relación con clientes\', CHANGE id_empresa id_empresa INT NOT NULL COMMENT \'Relación con empresas\', CHANGE fechayhora fechayhora DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE citas ADD CONSTRAINT citas_ibfk_1 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE citas ADD CONSTRAINT citas_ibfk_2 FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE citas ADD CONSTRAINT citas_ibfk_3 FOREIGN KEY (id_tipingreso) REFERENCES tipingresos (id_tipingreso) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE citas ADD CONSTRAINT citas_ibfk_4 FOREIGN KEY (id_vehiculo) REFERENCES vehiculos (id_vehiculo) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE clientes DROP FOREIGN KEY FK_50FE07D777309A3F');
        $this->addSql('ALTER TABLE clientes DROP FOREIGN KEY FK_50FE07D73BFFEBE1');
        $this->addSql('ALTER TABLE clientes DROP FOREIGN KEY FK_50FE07D78C422F77');
        $this->addSql('ALTER TABLE clientes CHANGE id_idioma id_idioma INT NOT NULL COMMENT \'Relación con los idiomas\', CHANGE id_tipcliente id_tipcliente INT NOT NULL COMMENT \'Relación con los tipos de cliente\', CHANGE activo activo TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE clientes ADD CONSTRAINT clientes_ibfk_1 FOREIGN KEY (id_tipcliente) REFERENCES tipclientes (id_tipcliente) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE clientes ADD CONSTRAINT clientes_ibfk_2 FOREIGN KEY (id_idioma) REFERENCES idiomas (id_idioma) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE clientes ADD CONSTRAINT clientes_ibfk_3 FOREIGN KEY (id_codpostal) REFERENCES codpostales (id_codpostal) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE codpostales DROP FOREIGN KEY FK_C049473A7EE3862E');
        $this->addSql('ALTER TABLE codpostales CHANGE id_poblacion id_poblacion INT NOT NULL COMMENT \'Relación con poblaciones\'');
        $this->addSql('ALTER TABLE codpostales ADD CONSTRAINT codpostales_ibfk_1 FOREIGN KEY (id_poblacion) REFERENCES poblaciones (id_poblacion) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE dencomerciales DROP FOREIGN KEY FK_38EC7CCA7EE963D3');
        $this->addSql('ALTER TABLE dencomerciales ADD CONSTRAINT dencomerciales_ibfk_1 FOREIGN KEY (id_fabricante) REFERENCES fabricantes (id_fabricante) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE detfacturas1 DROP FOREIGN KEY FK_7BA84394F760EA80');
        $this->addSql('ALTER TABLE detfacturas1 DROP FOREIGN KEY FK_7BA8439427760979');
        $this->addSql('ALTER TABLE detfacturas1 ADD CONSTRAINT detfacturas1_ibfk_1 FOREIGN KEY (id_factura) REFERENCES facturas (id_factura) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE detfacturas1 ADD CONSTRAINT detfacturas1_ibfk_2 FOREIGN KEY (id_producto) REFERENCES productos (id_producto) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE detfacturas2 DROP FOREIGN KEY FK_E2A1122E9B5D1EBF');
        $this->addSql('ALTER TABLE detfacturas2 DROP FOREIGN KEY FK_E2A1122E27760979');
        $this->addSql('ALTER TABLE detfacturas2 ADD CONSTRAINT detfacturas2_ibfk_1 FOREIGN KEY (id_factura) REFERENCES facturas (id_factura) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE detfacturas2 ADD CONSTRAINT detfacturas2_ibfk_2 FOREIGN KEY (id_servicio) REFERENCES servicios (id_servicio) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE detordenestrabajos1 DROP FOREIGN KEY FK_E36A4F0EF760EA80');
        $this->addSql('ALTER TABLE detordenestrabajos1 DROP FOREIGN KEY FK_E36A4F0ECFBF1E4A');
        $this->addSql('ALTER TABLE detordenestrabajos1 ADD CONSTRAINT detordenestrabajos1_ibfk_1 FOREIGN KEY (id_ordentrabajo) REFERENCES ordenestrabajos (id_ordentrabajo) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE detordenestrabajos1 ADD CONSTRAINT detordenestrabajos1_ibfk_2 FOREIGN KEY (id_producto) REFERENCES productos (id_producto) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE detordenestrabajos2 DROP FOREIGN KEY FK_7A631EB49B5D1EBF');
        $this->addSql('ALTER TABLE detordenestrabajos2 DROP FOREIGN KEY FK_7A631EB4CFBF1E4A');
        $this->addSql('ALTER TABLE detordenestrabajos2 ADD CONSTRAINT detordenestrabajos2_ibfk_1 FOREIGN KEY (id_ordentrabajo) REFERENCES ordenestrabajos (id_ordentrabajo) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE detordenestrabajos2 ADD CONSTRAINT detordenestrabajos2_ibfk_2 FOREIGN KEY (id_servicio) REFERENCES servicios (id_servicio) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE detpresupuestos1 DROP FOREIGN KEY FK_71AC57C4F760EA80');
        $this->addSql('ALTER TABLE detpresupuestos1 DROP FOREIGN KEY FK_71AC57C4371A524');
        $this->addSql('ALTER TABLE detpresupuestos1 ADD CONSTRAINT detpresupuestos1_ibfk_1 FOREIGN KEY (id_presupuesto) REFERENCES presupuestos (id_presupuesto) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE detpresupuestos1 ADD CONSTRAINT detpresupuestos1_ibfk_2 FOREIGN KEY (id_producto) REFERENCES productos (id_producto) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE detpresupuestos2 DROP FOREIGN KEY FK_E8A5067E9B5D1EBF');
        $this->addSql('ALTER TABLE detpresupuestos2 DROP FOREIGN KEY FK_E8A5067E371A524');
        $this->addSql('ALTER TABLE detpresupuestos2 ADD CONSTRAINT detpresupuestos2_ibfk_1 FOREIGN KEY (id_presupuesto) REFERENCES presupuestos (id_presupuesto) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE detpresupuestos2 ADD CONSTRAINT detpresupuestos2_ibfk_2 FOREIGN KEY (id_servicio) REFERENCES servicios (id_servicio) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE empleados DROP FOREIGN KEY FK_9EB2266C77309A3F');
        $this->addSql('ALTER TABLE empleados DROP FOREIGN KEY FK_9EB2266C3BFFEBE1');
        $this->addSql('ALTER TABLE empleados DROP FOREIGN KEY FK_9EB2266C5CC4D13E');
        $this->addSql('ALTER TABLE empleados CHANGE id_idioma id_idioma INT NOT NULL COMMENT \'Relación con los idiomas\', CHANGE id_tipempleado id_tipempleado INT NOT NULL COMMENT \'Relación con los tipos de empleado\', CHANGE activo activo TINYINT(1) DEFAULT \'0\', CHANGE autorizado autorizado TINYINT(1) DEFAULT \'1\'');
        $this->addSql('ALTER TABLE empleados ADD CONSTRAINT empleados_ibfk_1 FOREIGN KEY (id_tipempleado) REFERENCES tipempleados (id_tipempleado) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE empleados ADD CONSTRAINT empleados_ibfk_2 FOREIGN KEY (id_idioma) REFERENCES idiomas (id_idioma) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE empleados ADD CONSTRAINT empleados_ibfk_3 FOREIGN KEY (id_codpostal) REFERENCES codpostales (id_codpostal) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE empresas DROP FOREIGN KEY FK_70DD49A577309A3F');
        $this->addSql('ALTER TABLE empresas DROP FOREIGN KEY FK_70DD49A53BFFEBE1');
        $this->addSql('ALTER TABLE empresas CHANGE id_idioma id_idioma INT NOT NULL COMMENT \'Relación con los idiomas\', CHANGE activo activo TINYINT(1) DEFAULT \'0\', CHANGE autorizado autorizado TINYINT(1) DEFAULT \'1\', CHANGE proveedor proveedor TINYINT(1) DEFAULT \'0\', CHANGE concesionario concesionario TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE empresas ADD CONSTRAINT empresas_ibfk_1 FOREIGN KEY (id_idioma) REFERENCES idiomas (id_idioma) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE empresas ADD CONSTRAINT empresas_ibfk_2 FOREIGN KEY (id_codpostal) REFERENCES codpostales (id_codpostal) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE entradasosalidas DROP FOREIGN KEY FK_7A4F7947F760EA80');
        $this->addSql('ALTER TABLE entradasosalidas DROP FOREIGN KEY FK_7A4F7947664AF320');
        $this->addSql('ALTER TABLE entradasosalidas CHANGE fecentradaosalida fecentradaosalida DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE entradasosalidas ADD CONSTRAINT entradasosalidas_ibfk_1 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE entradasosalidas ADD CONSTRAINT entradasosalidas_ibfk_2 FOREIGN KEY (id_producto) REFERENCES productos (id_producto) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE facturas DROP FOREIGN KEY FK_622B9C0F5864BC49');
        $this->addSql('ALTER TABLE facturas DROP FOREIGN KEY FK_622B9C0FCFBF1E4A');
        $this->addSql('ALTER TABLE facturas DROP FOREIGN KEY FK_622B9C0F2A813255');
        $this->addSql('ALTER TABLE facturas DROP FOREIGN KEY FK_622B9C0FD37F13FC');
        $this->addSql('ALTER TABLE facturas DROP FOREIGN KEY FK_622B9C0F371A524');
        $this->addSql('ALTER TABLE facturas DROP FOREIGN KEY FK_622B9C0F12068D6F');
        $this->addSql('ALTER TABLE facturas DROP FOREIGN KEY FK_622B9C0F664AF320');
        $this->addSql('ALTER TABLE facturas CHANGE fecha fecha DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT facturas_ibfk_1 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT facturas_ibfk_2 FOREIGN KEY (id_presupuesto) REFERENCES presupuestos (id_presupuesto) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT facturas_ibfk_3 FOREIGN KEY (id_ingreso) REFERENCES ingresos (id_ingreso) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT facturas_ibfk_4 FOREIGN KEY (id_tipaccion) REFERENCES tipacciones (id_tipaccion) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT facturas_ibfk_5 FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT facturas_ibfk_6 FOREIGN KEY (id_tippago) REFERENCES tippagos (id_tippago) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT facturas_ibfk_7 FOREIGN KEY (id_ordentrabajo) REFERENCES ordenestrabajos (id_ordentrabajo) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE idiomas DROP FOREIGN KEY FK_12A54B7EF57D32FD');
        $this->addSql('ALTER TABLE idiomas CHANGE id_pais id_pais INT NOT NULL COMMENT \'Relación con banderas de países\'');
        $this->addSql('ALTER TABLE idiomas ADD CONSTRAINT idiomas_ibfk_1 FOREIGN KEY (id_pais) REFERENCES paises (id_pais) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE ingresos DROP FOREIGN KEY FK_96CA59DAB4C5904D');
        $this->addSql('ALTER TABLE ingresos DROP FOREIGN KEY FK_96CA59DA6A540E');
        $this->addSql('ALTER TABLE ingresos DROP FOREIGN KEY FK_96CA59DA9921FA96');
        $this->addSql('ALTER TABLE ingresos DROP FOREIGN KEY FK_96CA59DA2A813255');
        $this->addSql('ALTER TABLE ingresos DROP FOREIGN KEY FK_96CA59DA664AF320');
        $this->addSql('ALTER TABLE ingresos CHANGE fyhingreso fyhingreso DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE fyhinicio fyhinicio DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, CHANGE fyhfinalizacion fyhfinalizacion DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, CHANGE fyhentrega fyhentrega DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL');
        $this->addSql('ALTER TABLE ingresos ADD CONSTRAINT ingresos_ibfk_1 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE ingresos ADD CONSTRAINT ingresos_ibfk_2 FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE ingresos ADD CONSTRAINT ingresos_ibfk_3 FOREIGN KEY (id_vehiculo) REFERENCES vehiculos (id_vehiculo) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE ingresos ADD CONSTRAINT ingresos_ibfk_4 FOREIGN KEY (id_estado) REFERENCES estados (id_estado) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE ingresos ADD CONSTRAINT ingresos_ibfk_5 FOREIGN KEY (id_tipingreso) REFERENCES tipingresos (id_tipingreso) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE inventarios DROP FOREIGN KEY FK_D6B3D0D6F760EA80');
        $this->addSql('ALTER TABLE inventarios DROP FOREIGN KEY FK_D6B3D0D6664AF320');
        $this->addSql('ALTER TABLE inventarios ADD CONSTRAINT inventarios_ibfk_1 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE inventarios ADD CONSTRAINT inventarios_ibfk_2 FOREIGN KEY (id_producto) REFERENCES productos (id_producto) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE modelos DROP FOREIGN KEY FK_8441FCC2A253177B');
        $this->addSql('ALTER TABLE modelos DROP FOREIGN KEY FK_8441FCC27EE963D3');
        $this->addSql('ALTER TABLE modelos DROP FOREIGN KEY FK_8441FCC24CE7786F');
        $this->addSql('ALTER TABLE modelos DROP FOREIGN KEY FK_8441FCC296F53A11');
        $this->addSql('ALTER TABLE modelos ADD CONSTRAINT modelos_ibfk_1 FOREIGN KEY (id_dencomercial) REFERENCES dencomerciales (id_dencomercial) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE modelos ADD CONSTRAINT modelos_ibfk_2 FOREIGN KEY (id_tipvehiculo) REFERENCES tipvehiculos (id_tipvehiculo) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE modelos ADD CONSTRAINT modelos_ibfk_3 FOREIGN KEY (id_fabricante) REFERENCES fabricantes (id_fabricante) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE modelos ADD CONSTRAINT modelos_ibfk_4 FOREIGN KEY (id_tipcombustible) REFERENCES tipcombustibles (id_tipcombustible) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE ordenestrabajos DROP FOREIGN KEY FK_D699FB7F12068D6F');
        $this->addSql('ALTER TABLE ordenestrabajos DROP FOREIGN KEY FK_D699FB7F890253C7');
        $this->addSql('ALTER TABLE ordenestrabajos DROP FOREIGN KEY FK_D699FB7F664AF320');
        $this->addSql('ALTER TABLE ordenestrabajos CHANGE fecha fecha DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE presupuestado presupuestado TINYINT(1) DEFAULT \'0\', CHANGE facturado facturado TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE ordenestrabajos ADD CONSTRAINT ordenestrabajos_ibfk_1 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE ordenestrabajos ADD CONSTRAINT ordenestrabajos_ibfk_2 FOREIGN KEY (id_empleado) REFERENCES empleados (id_empleado) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE ordenestrabajos ADD CONSTRAINT ordenestrabajos_ibfk_3 FOREIGN KEY (id_ingreso) REFERENCES ingresos (id_ingreso) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE paises DROP FOREIGN KEY FK_DFAD237BE63DD634');
        $this->addSql('ALTER TABLE paises DROP FOREIGN KEY FK_DFAD237B963C9EC0');
        $this->addSql('ALTER TABLE paises ADD CONSTRAINT paises_ibfk_1 FOREIGN KEY (id_moneda) REFERENCES monedas (id_moneda) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE paises ADD CONSTRAINT paises_ibfk_2 FOREIGN KEY (id_impuesto) REFERENCES impuestos (id_impuesto) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE poblaciones DROP FOREIGN KEY FK_879131B653AF4E34');
        $this->addSql('ALTER TABLE poblaciones CHANGE id_provincia id_provincia INT NOT NULL COMMENT \'Relación con provincias\'');
        $this->addSql('ALTER TABLE poblaciones ADD CONSTRAINT poblaciones_ibfk_1 FOREIGN KEY (id_provincia) REFERENCES provincias (id_provincia) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE presupuestos DROP FOREIGN KEY FK_4CF2F0DCFBF1E4A');
        $this->addSql('ALTER TABLE presupuestos DROP FOREIGN KEY FK_4CF2F0D2A813255');
        $this->addSql('ALTER TABLE presupuestos DROP FOREIGN KEY FK_4CF2F0DD37F13FC');
        $this->addSql('ALTER TABLE presupuestos DROP FOREIGN KEY FK_4CF2F0D12068D6F');
        $this->addSql('ALTER TABLE presupuestos DROP FOREIGN KEY FK_4CF2F0D664AF320');
        $this->addSql('ALTER TABLE presupuestos CHANGE fecha fecha DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE avisado avisado TINYINT(1) DEFAULT \'0\', CHANGE facturado facturado TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE presupuestos ADD CONSTRAINT presupuestos_ibfk_1 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE presupuestos ADD CONSTRAINT presupuestos_ibfk_2 FOREIGN KEY (id_ingreso) REFERENCES ingresos (id_ingreso) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE presupuestos ADD CONSTRAINT presupuestos_ibfk_3 FOREIGN KEY (id_tipaccion) REFERENCES tipacciones (id_tipaccion) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE presupuestos ADD CONSTRAINT presupuestos_ibfk_4 FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE presupuestos ADD CONSTRAINT presupuestos_ibfk_5 FOREIGN KEY (id_ordentrabajo) REFERENCES ordenestrabajos (id_ordentrabajo) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE productos DROP FOREIGN KEY FK_767490E680F46B3F');
        $this->addSql('ALTER TABLE productos DROP FOREIGN KEY FK_767490E6E98F4023');
        $this->addSql('ALTER TABLE productos ADD CONSTRAINT productos_ibfk_1 FOREIGN KEY (id_marca) REFERENCES marcas (id_marca) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE productos ADD CONSTRAINT productos_ibfk_2 FOREIGN KEY (id_familia) REFERENCES familias (id_familia) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE provincias DROP FOREIGN KEY FK_9F631427F57D32FD');
        $this->addSql('ALTER TABLE provincias CHANGE id_pais id_pais INT NOT NULL COMMENT \'Relación con paises\'');
        $this->addSql('ALTER TABLE provincias ADD CONSTRAINT provincias_ibfk_1 FOREIGN KEY (id_pais) REFERENCES paises (id_pais) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relempresasclientes DROP FOREIGN KEY FK_EBB782BE2A813255');
        $this->addSql('ALTER TABLE relempresasclientes DROP FOREIGN KEY FK_EBB782BE664AF320');
        $this->addSql('ALTER TABLE relempresasclientes CHANGE id_cliente id_cliente INT NOT NULL COMMENT \'Relación con los clientes\', CHANGE id_empresa id_empresa INT NOT NULL COMMENT \'Relación con las empresas\', CHANGE fecalta fecalta DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE relempresasclientes ADD CONSTRAINT relempresasclientes_ibfk_1 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relempresasclientes ADD CONSTRAINT relempresasclientes_ibfk_2 FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relempresascuecorrientes DROP FOREIGN KEY FK_1CDE511B3971CE23');
        $this->addSql('ALTER TABLE relempresascuecorrientes DROP FOREIGN KEY FK_1CDE511B664AF320');
        $this->addSql('ALTER TABLE relempresascuecorrientes ADD CONSTRAINT relempresascuecorrientes_ibfk_1 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relempresascuecorrientes ADD CONSTRAINT relempresascuecorrientes_ibfk_2 FOREIGN KEY (id_entbancaria) REFERENCES entbancarias (id_entbancaria) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relempresasemails DROP FOREIGN KEY FK_3C73317BA25C2750');
        $this->addSql('ALTER TABLE relempresasemails DROP FOREIGN KEY FK_3C73317B664AF320');
        $this->addSql('ALTER TABLE relempresasemails CHANGE id_tipcontacto id_tipcontacto INT NOT NULL COMMENT \'Relación con tipos de contacto\', CHANGE id_empresa id_empresa INT NOT NULL COMMENT \'Relación con empresas\'');
        $this->addSql('ALTER TABLE relempresasemails ADD CONSTRAINT relempresasemails_ibfk_1 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relempresasemails ADD CONSTRAINT relempresasemails_ibfk_2 FOREIGN KEY (id_tipcontacto) REFERENCES tipcontactos (id_tipcontacto) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relempresasempleados DROP FOREIGN KEY FK_AA67B615890253C7');
        $this->addSql('ALTER TABLE relempresasempleados DROP FOREIGN KEY FK_AA67B615664AF320');
        $this->addSql('ALTER TABLE relempresasempleados CHANGE id_empleado id_empleado INT NOT NULL COMMENT \'Relación con empleados\', CHANGE id_empresa id_empresa INT NOT NULL COMMENT \'Relación con empresas\', CHANGE fecalta fecalta DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE despedido despedido TINYINT(1) DEFAULT \'0\', CHANGE fecbaja fecbaja DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL');
        $this->addSql('ALTER TABLE relempresasempleados ADD CONSTRAINT relempresasempleados_ibfk_1 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relempresasempleados ADD CONSTRAINT relempresasempleados_ibfk_2 FOREIGN KEY (id_empleado) REFERENCES empleados (id_empleado) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relempresasfabricantes DROP FOREIGN KEY FK_124A0DDF7EE963D3');
        $this->addSql('ALTER TABLE relempresasfabricantes DROP FOREIGN KEY FK_124A0DDF664AF320');
        $this->addSql('ALTER TABLE relempresasfabricantes CHANGE id_fabricante id_fabricante INT NOT NULL COMMENT \'Relación con fabricantes\', CHANGE id_empresa id_empresa INT NOT NULL COMMENT \'Relación con empresas\'');
        $this->addSql('ALTER TABLE relempresasfabricantes ADD CONSTRAINT relempresasfabricantes_ibfk_1 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relempresasfabricantes ADD CONSTRAINT relempresasfabricantes_ibfk_2 FOREIGN KEY (id_fabricante) REFERENCES fabricantes (id_fabricante) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relempresasroductos DROP FOREIGN KEY FK_BEB51D9DF760EA80');
        $this->addSql('ALTER TABLE relempresasroductos DROP FOREIGN KEY FK_BEB51D9D664AF320');
        $this->addSql('ALTER TABLE relempresasroductos ADD CONSTRAINT relempresasroductos_ibfk_1 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relempresasroductos ADD CONSTRAINT relempresasroductos_ibfk_2 FOREIGN KEY (id_producto) REFERENCES productos (id_producto) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relempresasservicios DROP FOREIGN KEY FK_F4AB10569B5D1EBF');
        $this->addSql('ALTER TABLE relempresasservicios DROP FOREIGN KEY FK_F4AB1056664AF320');
        $this->addSql('ALTER TABLE relempresasservicios ADD CONSTRAINT relempresasservicios_ibfk_1 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relempresasservicios ADD CONSTRAINT relempresasservicios_ibfk_2 FOREIGN KEY (id_servicio) REFERENCES servicios (id_servicio) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relempresastelefonos DROP FOREIGN KEY FK_EFA0D4D5A25C2750');
        $this->addSql('ALTER TABLE relempresastelefonos DROP FOREIGN KEY FK_EFA0D4D5664AF320');
        $this->addSql('ALTER TABLE relempresastelefonos CHANGE id_tipcontacto id_tipcontacto INT NOT NULL COMMENT \'Relación con tipos de contacto\', CHANGE id_empresa id_empresa INT NOT NULL COMMENT \'Relación con empresas\'');
        $this->addSql('ALTER TABLE relempresastelefonos ADD CONSTRAINT relempresastelefonos_ibfk_1 FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relempresastelefonos ADD CONSTRAINT relempresastelefonos_ibfk_2 FOREIGN KEY (id_tipcontacto) REFERENCES tipcontactos (id_tipcontacto) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relmodelosproductos DROP FOREIGN KEY FK_F0D9213BF760EA80');
        $this->addSql('ALTER TABLE relmodelosproductos DROP FOREIGN KEY FK_F0D9213BD6E0D9AB');
        $this->addSql('ALTER TABLE relmodelosproductos ADD CONSTRAINT relmodelosproductos_ibfk_1 FOREIGN KEY (id_modelo) REFERENCES modelos (id_modelo) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relmodelosproductos ADD CONSTRAINT relmodelosproductos_ibfk_2 FOREIGN KEY (id_producto) REFERENCES productos (id_producto) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relmodelosservicios DROP FOREIGN KEY FK_46D331F29B5D1EBF');
        $this->addSql('ALTER TABLE relmodelosservicios DROP FOREIGN KEY FK_46D331F2D6E0D9AB');
        $this->addSql('ALTER TABLE relmodelosservicios ADD CONSTRAINT relmodelosservicios_ibfk_1 FOREIGN KEY (id_modelo) REFERENCES modelos (id_modelo) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relmodelosservicios ADD CONSTRAINT relmodelosservicios_ibfk_2 FOREIGN KEY (id_servicio) REFERENCES servicios (id_servicio) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relproductosproductos DROP FOREIGN KEY FK_B0591DB5F79A5DC7');
        $this->addSql('ALTER TABLE relproductosproductos DROP FOREIGN KEY FK_B0591DB56E930C7D');
        $this->addSql('ALTER TABLE relproductosproductos ADD CONSTRAINT relproductosproductos_ibfk_1 FOREIGN KEY (id_producto1) REFERENCES productos (id_producto) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE relproductosproductos ADD CONSTRAINT relproductosproductos_ibfk_2 FOREIGN KEY (id_producto2) REFERENCES productos (id_producto) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE vehiculos DROP FOREIGN KEY FK_82CE64A7D6E0D9AB');
        $this->addSql('ALTER TABLE vehiculos DROP FOREIGN KEY FK_82CE64A72A813255');
        $this->addSql('ALTER TABLE vehiculos DROP FOREIGN KEY FK_82CE64A7F57D32FD');
        $this->addSql('ALTER TABLE vehiculos CHANGE fecmatriculacion fecmatriculacion DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE fecfabricacion fecfabricacion DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, CHANGE fecitv fecitv DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, CHANGE fecmantenimiento fecmantenimiento DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL');
        $this->addSql('ALTER TABLE vehiculos ADD CONSTRAINT vehiculos_ibfk_1 FOREIGN KEY (id_pais) REFERENCES paises (id_pais) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE vehiculos ADD CONSTRAINT vehiculos_ibfk_2 FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE vehiculos ADD CONSTRAINT vehiculos_ibfk_3 FOREIGN KEY (id_modelo) REFERENCES modelos (id_modelo) ON UPDATE CASCADE');
    }
}
