<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150617032415 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP INDEX estado_1 ON estados');
        $this->addSql('DROP INDEX estado_2 ON estados');
        $this->addSql('DROP INDEX estado_3 ON estados');
        $this->addSql('DROP INDEX estado_4 ON estados');
        $this->addSql('DROP INDEX estado_5 ON estados');
        $this->addSql('DROP INDEX estado_6 ON estados');
        $this->addSql('ALTER TABLE estados DROP estado_2, DROP estado_3, DROP estado_4, DROP estado_5, DROP estado_6, CHANGE estado_1 estado VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX estado ON estados (estado)');
        $this->addSql('DROP INDEX familia_1 ON familias');
        $this->addSql('DROP INDEX familia_2 ON familias');
        $this->addSql('DROP INDEX familia_3 ON familias');
        $this->addSql('DROP INDEX familia_4 ON familias');
        $this->addSql('DROP INDEX familia_5 ON familias');
        $this->addSql('DROP INDEX familia_6 ON familias');
        $this->addSql('ALTER TABLE familias DROP familia_2, DROP familia_3, DROP familia_4, DROP familia_5, DROP familia_6, CHANGE familia_1 familia VARCHAR(40) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX familia ON familias (familia)');
        $this->addSql('DROP INDEX idioma_1 ON idiomas');
        $this->addSql('DROP INDEX idioma_2 ON idiomas');
        $this->addSql('DROP INDEX idioma_3 ON idiomas');
        $this->addSql('DROP INDEX idioma_4 ON idiomas');
        $this->addSql('DROP INDEX idioma_5 ON idiomas');
        $this->addSql('DROP INDEX idioma_6 ON idiomas');
        $this->addSql('ALTER TABLE idiomas DROP idioma_2, DROP idioma_3, DROP idioma_4, DROP idioma_5, DROP idioma_6, CHANGE idioma_1 idioma VARCHAR(30) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX idioma ON idiomas (idioma)');
        $this->addSql('DROP INDEX moneda_1 ON monedas');
        $this->addSql('DROP INDEX moneda_2 ON monedas');
        $this->addSql('DROP INDEX moneda_3 ON monedas');
        $this->addSql('DROP INDEX moneda_4 ON monedas');
        $this->addSql('DROP INDEX moneda_5 ON monedas');
        $this->addSql('DROP INDEX moneda_6 ON monedas');
        $this->addSql('ALTER TABLE monedas DROP moneda_2, DROP moneda_3, DROP moneda_4, DROP moneda_5, DROP moneda_6, CHANGE moneda_1 moneda VARCHAR(30) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX moneda ON monedas (moneda)');
        $this->addSql('DROP INDEX pais_1 ON paises');
        $this->addSql('DROP INDEX pais_2 ON paises');
        $this->addSql('DROP INDEX pais_3 ON paises');
        $this->addSql('DROP INDEX pais_4 ON paises');
        $this->addSql('DROP INDEX pais_5 ON paises');
        $this->addSql('DROP INDEX pais_6 ON paises');
        $this->addSql('ALTER TABLE paises DROP pais_2, DROP pais_3, DROP pais_4, DROP pais_5, DROP pais_6, CHANGE pais_1 pais VARCHAR(50) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX pais ON paises (pais)');
        $this->addSql('DROP INDEX poblacion_1 ON poblaciones');
        $this->addSql('DROP INDEX poblacion_2 ON poblaciones');
        $this->addSql('DROP INDEX poblacion_3 ON poblaciones');
        $this->addSql('DROP INDEX poblacion_4 ON poblaciones');
        $this->addSql('DROP INDEX poblacion_5 ON poblaciones');
        $this->addSql('DROP INDEX poblacion_6 ON poblaciones');
        $this->addSql('ALTER TABLE poblaciones ADD poblacion VARCHAR(50) NOT NULL, DROP poblacion_1, DROP poblacion_2, DROP poblacion_3, DROP poblacion_4, DROP poblacion_5, DROP poblacion_6');
        $this->addSql('CREATE UNIQUE INDEX poblacion ON poblaciones (poblacion)');
        $this->addSql('DROP INDEX descripcion_1 ON productos');
        $this->addSql('DROP INDEX descripcion_2 ON productos');
        $this->addSql('DROP INDEX descripcion_3 ON productos');
        $this->addSql('DROP INDEX descripcion_4 ON productos');
        $this->addSql('DROP INDEX descripcion_5 ON productos');
        $this->addSql('DROP INDEX descripcion_6 ON productos');
        $this->addSql('ALTER TABLE productos DROP descripcion_2, DROP descripcion_3, DROP descripcion_4, DROP descripcion_5, DROP descripcion_6, CHANGE descripcion_1 descripcion VARCHAR(50) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX descripcion ON productos (descripcion)');
        $this->addSql('DROP INDEX provincia_1 ON provincias');
        $this->addSql('DROP INDEX provincia_2 ON provincias');
        $this->addSql('DROP INDEX provincia_3 ON provincias');
        $this->addSql('DROP INDEX provincia_4 ON provincias');
        $this->addSql('DROP INDEX provincia_5 ON provincias');
        $this->addSql('DROP INDEX provincia_6 ON provincias');
        $this->addSql('ALTER TABLE provincias DROP provincia_2, DROP provincia_3, DROP provincia_4, DROP provincia_5, DROP provincia_6, CHANGE provincia_1 provincia VARCHAR(50) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX provincia ON provincias (provincia)');
        $this->addSql('DROP INDEX servicio_1 ON servicios');
        $this->addSql('DROP INDEX servicio_2 ON servicios');
        $this->addSql('DROP INDEX servicio_3 ON servicios');
        $this->addSql('DROP INDEX servicio_4 ON servicios');
        $this->addSql('DROP INDEX servicio_5 ON servicios');
        $this->addSql('DROP INDEX servicio_6 ON servicios');
        $this->addSql('ALTER TABLE servicios DROP servicio_2, DROP servicio_3, DROP servicio_4, DROP servicio_5, DROP servicio_6, CHANGE servicio_1 servicio VARCHAR(50) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX servicio ON servicios (servicio)');
        $this->addSql('DROP INDEX tipaccion_1 ON tipacciones');
        $this->addSql('DROP INDEX tipaccion_2 ON tipacciones');
        $this->addSql('DROP INDEX tipaccion_3 ON tipacciones');
        $this->addSql('DROP INDEX tipaccion_4 ON tipacciones');
        $this->addSql('DROP INDEX tipaccion_5 ON tipacciones');
        $this->addSql('DROP INDEX tipaccion_6 ON tipacciones');
        $this->addSql('ALTER TABLE tipacciones DROP tipaccion_2, DROP tipaccion_3, DROP tipaccion_4, DROP tipaccion_5, DROP tipaccion_6, CHANGE tipaccion_1 tipaccion VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX tipaccion ON tipacciones (tipaccion)');
        $this->addSql('DROP INDEX tipcliente_2 ON tipclientes');
        $this->addSql('DROP INDEX tipcliente_3 ON tipclientes');
        $this->addSql('DROP INDEX tipcliente_4 ON tipclientes');
        $this->addSql('DROP INDEX tipcliente_5 ON tipclientes');
        $this->addSql('DROP INDEX tipcliente_6 ON tipclientes');
        $this->addSql('ALTER TABLE tipclientes DROP tipcliente_2, DROP tipcliente_3, DROP tipcliente_4, DROP tipcliente_5, DROP tipcliente_6, CHANGE tipcliente_1 tipcliente VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX tipcliente ON tipclientes (tipcliente)');
        $this->addSql('DROP INDEX tipcombustible_1 ON tipcombustibles');
        $this->addSql('DROP INDEX tipcombustible_2 ON tipcombustibles');
        $this->addSql('DROP INDEX tipcombustible_3 ON tipcombustibles');
        $this->addSql('DROP INDEX tipcombustible_4 ON tipcombustibles');
        $this->addSql('DROP INDEX tipcombustible_5 ON tipcombustibles');
        $this->addSql('DROP INDEX tipcombustible_6 ON tipcombustibles');
        $this->addSql('ALTER TABLE tipcombustibles DROP tipcombustible_2, DROP tipcombustible_3, DROP tipcombustible_4, DROP tipcombustible_5, DROP tipcombustible_6, CHANGE tipcombustible_1 tipcombustible VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX tipcombustible ON tipcombustibles (tipcombustible)');
        $this->addSql('DROP INDEX tipcontacto_1 ON tipcontactos');
        $this->addSql('DROP INDEX tipcontacto_2 ON tipcontactos');
        $this->addSql('DROP INDEX tipcontacto_3 ON tipcontactos');
        $this->addSql('DROP INDEX tipcontacto_4 ON tipcontactos');
        $this->addSql('DROP INDEX tipcontacto_5 ON tipcontactos');
        $this->addSql('DROP INDEX tipcontacto_6 ON tipcontactos');
        $this->addSql('ALTER TABLE tipcontactos DROP tipcontacto_2, DROP tipcontacto_3, DROP tipcontacto_4, DROP tipcontacto_5, DROP tipcontacto_6, CHANGE tipcontacto_1 tipcontacto VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX tipcontacto ON tipcontactos (tipcontacto)');
        $this->addSql('DROP INDEX tipempleado_1 ON tipempleados');
        $this->addSql('DROP INDEX tipempleado_2 ON tipempleados');
        $this->addSql('DROP INDEX tipempleado_3 ON tipempleados');
        $this->addSql('DROP INDEX tipempleado_4 ON tipempleados');
        $this->addSql('DROP INDEX tipempleado_5 ON tipempleados');
        $this->addSql('DROP INDEX tipempleado_6 ON tipempleados');
        $this->addSql('ALTER TABLE tipempleados DROP tipempleado_2, DROP tipempleado_3, DROP tipempleado_4, DROP tipempleado_5, DROP tipempleado_6, CHANGE tipempleado_1 tipempleado VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX tipempleado ON tipempleados (tipempleado)');
        $this->addSql('DROP INDEX tipingreso_1 ON tipingresos');
        $this->addSql('DROP INDEX tipingreso_2 ON tipingresos');
        $this->addSql('DROP INDEX tipingreso_3 ON tipingresos');
        $this->addSql('DROP INDEX tipingreso_4 ON tipingresos');
        $this->addSql('DROP INDEX tipingreso_5 ON tipingresos');
        $this->addSql('DROP INDEX tipingreso_6 ON tipingresos');
        $this->addSql('ALTER TABLE tipingresos DROP tipingreso_2, DROP tipingreso_3, DROP tipingreso_4, DROP tipingreso_5, DROP tipingreso_6, CHANGE tipingreso_1 tipingreso VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX tipingreso ON tipingresos (tipingreso)');
        $this->addSql('DROP INDEX tippago_1 ON tippagos');
        $this->addSql('DROP INDEX tippago_2 ON tippagos');
        $this->addSql('DROP INDEX tippago_3 ON tippagos');
        $this->addSql('DROP INDEX tippago_4 ON tippagos');
        $this->addSql('DROP INDEX tippago_5 ON tippagos');
        $this->addSql('DROP INDEX tippago_6 ON tippagos');
        $this->addSql('ALTER TABLE tippagos DROP tippago_2, DROP tippago_3, DROP tippago_4, DROP tippago_5, DROP tippago_6, CHANGE tippago_1 tippago VARCHAR(30) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX tippago ON tippagos (tippago)');
        $this->addSql('DROP INDEX tipvehiculo_1 ON tipvehiculos');
        $this->addSql('DROP INDEX clasificacion ON tipvehiculos');
        $this->addSql('DROP INDEX tipvehiculo_2 ON tipvehiculos');
        $this->addSql('DROP INDEX tipvehiculo_3 ON tipvehiculos');
        $this->addSql('DROP INDEX tipvehiculo_4 ON tipvehiculos');
        $this->addSql('DROP INDEX tipvehiculo_5 ON tipvehiculos');
        $this->addSql('DROP INDEX tipvehiculo_6 ON tipvehiculos');
        $this->addSql('ALTER TABLE tipvehiculos DROP tipvehiculo_2, DROP tipvehiculo_3, DROP tipvehiculo_4, DROP tipvehiculo_5, DROP tipvehiculo_6, CHANGE tipvehiculo_1 tipvehiculo VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX tipvehiculo ON tipvehiculos (tipvehiculo)');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP INDEX estado ON estados');
        $this->addSql('ALTER TABLE estados ADD estado_2 VARCHAR(30) DEFAULT NULL, ADD estado_3 VARCHAR(30) DEFAULT NULL, ADD estado_4 VARCHAR(30) DEFAULT NULL, ADD estado_5 VARCHAR(30) DEFAULT NULL, ADD estado_6 VARCHAR(30) DEFAULT NULL, CHANGE estado estado_1 VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX estado_1 ON estados (estado_1)');
        $this->addSql('CREATE UNIQUE INDEX estado_2 ON estados (estado_2)');
        $this->addSql('CREATE UNIQUE INDEX estado_3 ON estados (estado_3)');
        $this->addSql('CREATE UNIQUE INDEX estado_4 ON estados (estado_4)');
        $this->addSql('CREATE UNIQUE INDEX estado_5 ON estados (estado_5)');
        $this->addSql('CREATE UNIQUE INDEX estado_6 ON estados (estado_6)');
        $this->addSql('DROP INDEX familia ON familias');
        $this->addSql('ALTER TABLE familias ADD familia_2 VARCHAR(40) DEFAULT NULL, ADD familia_3 VARCHAR(40) DEFAULT NULL, ADD familia_4 VARCHAR(40) DEFAULT NULL, ADD familia_5 VARCHAR(40) DEFAULT NULL, ADD familia_6 VARCHAR(40) DEFAULT NULL, CHANGE familia familia_1 VARCHAR(40) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX familia_1 ON familias (familia_1)');
        $this->addSql('CREATE UNIQUE INDEX familia_2 ON familias (familia_2)');
        $this->addSql('CREATE UNIQUE INDEX familia_3 ON familias (familia_3)');
        $this->addSql('CREATE UNIQUE INDEX familia_4 ON familias (familia_4)');
        $this->addSql('CREATE UNIQUE INDEX familia_5 ON familias (familia_5)');
        $this->addSql('CREATE UNIQUE INDEX familia_6 ON familias (familia_6)');
        $this->addSql('DROP INDEX idioma ON idiomas');
        $this->addSql('ALTER TABLE idiomas ADD idioma_2 VARCHAR(30) DEFAULT NULL, ADD idioma_3 VARCHAR(30) DEFAULT NULL, ADD idioma_4 VARCHAR(30) DEFAULT NULL, ADD idioma_5 VARCHAR(30) DEFAULT NULL, ADD idioma_6 VARCHAR(30) DEFAULT NULL, CHANGE idioma idioma_1 VARCHAR(30) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX idioma_1 ON idiomas (idioma_1)');
        $this->addSql('CREATE UNIQUE INDEX idioma_2 ON idiomas (idioma_2)');
        $this->addSql('CREATE UNIQUE INDEX idioma_3 ON idiomas (idioma_3)');
        $this->addSql('CREATE UNIQUE INDEX idioma_4 ON idiomas (idioma_4)');
        $this->addSql('CREATE UNIQUE INDEX idioma_5 ON idiomas (idioma_5)');
        $this->addSql('CREATE UNIQUE INDEX idioma_6 ON idiomas (idioma_6)');
        $this->addSql('DROP INDEX moneda ON monedas');
        $this->addSql('ALTER TABLE monedas ADD moneda_2 VARCHAR(30) DEFAULT NULL, ADD moneda_3 VARCHAR(30) DEFAULT NULL, ADD moneda_4 VARCHAR(30) DEFAULT NULL, ADD moneda_5 VARCHAR(30) DEFAULT NULL, ADD moneda_6 VARCHAR(30) DEFAULT NULL, CHANGE moneda moneda_1 VARCHAR(30) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX moneda_1 ON monedas (moneda_1)');
        $this->addSql('CREATE UNIQUE INDEX moneda_2 ON monedas (moneda_2)');
        $this->addSql('CREATE UNIQUE INDEX moneda_3 ON monedas (moneda_3)');
        $this->addSql('CREATE UNIQUE INDEX moneda_4 ON monedas (moneda_4)');
        $this->addSql('CREATE UNIQUE INDEX moneda_5 ON monedas (moneda_5)');
        $this->addSql('CREATE UNIQUE INDEX moneda_6 ON monedas (moneda_6)');
        $this->addSql('DROP INDEX pais ON paises');
        $this->addSql('ALTER TABLE paises ADD pais_2 VARCHAR(50) DEFAULT NULL, ADD pais_3 VARCHAR(50) DEFAULT NULL, ADD pais_4 VARCHAR(50) DEFAULT NULL, ADD pais_5 VARCHAR(50) DEFAULT NULL, ADD pais_6 VARCHAR(50) DEFAULT NULL, CHANGE pais pais_1 VARCHAR(50) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX pais_1 ON paises (pais_1)');
        $this->addSql('CREATE UNIQUE INDEX pais_2 ON paises (pais_2)');
        $this->addSql('CREATE UNIQUE INDEX pais_3 ON paises (pais_3)');
        $this->addSql('CREATE UNIQUE INDEX pais_4 ON paises (pais_4)');
        $this->addSql('CREATE UNIQUE INDEX pais_5 ON paises (pais_5)');
        $this->addSql('CREATE UNIQUE INDEX pais_6 ON paises (pais_6)');
        $this->addSql('DROP INDEX poblacion ON poblaciones');
        $this->addSql('ALTER TABLE poblaciones ADD poblacion_2 VARCHAR(50) NOT NULL, ADD poblacion_3 VARCHAR(50) NOT NULL, ADD poblacion_4 VARCHAR(50) NOT NULL, ADD poblacion_5 VARCHAR(50) NOT NULL, ADD poblacion_6 VARCHAR(50) NOT NULL, CHANGE poblacion poblacion_1 VARCHAR(50) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX poblacion_1 ON poblaciones (poblacion_1)');
        $this->addSql('CREATE UNIQUE INDEX poblacion_2 ON poblaciones (poblacion_2)');
        $this->addSql('CREATE UNIQUE INDEX poblacion_3 ON poblaciones (poblacion_3)');
        $this->addSql('CREATE UNIQUE INDEX poblacion_4 ON poblaciones (poblacion_4)');
        $this->addSql('CREATE UNIQUE INDEX poblacion_5 ON poblaciones (poblacion_5)');
        $this->addSql('CREATE UNIQUE INDEX poblacion_6 ON poblaciones (poblacion_6)');
        $this->addSql('DROP INDEX descripcion ON productos');
        $this->addSql('ALTER TABLE productos ADD descripcion_2 VARCHAR(50) DEFAULT NULL, ADD descripcion_3 VARCHAR(50) DEFAULT NULL, ADD descripcion_4 VARCHAR(50) DEFAULT NULL, ADD descripcion_5 VARCHAR(50) DEFAULT NULL, ADD descripcion_6 VARCHAR(50) DEFAULT NULL, CHANGE descripcion descripcion_1 VARCHAR(50) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX descripcion_1 ON productos (descripcion_1)');
        $this->addSql('CREATE UNIQUE INDEX descripcion_2 ON productos (descripcion_2)');
        $this->addSql('CREATE UNIQUE INDEX descripcion_3 ON productos (descripcion_3)');
        $this->addSql('CREATE UNIQUE INDEX descripcion_4 ON productos (descripcion_4)');
        $this->addSql('CREATE UNIQUE INDEX descripcion_5 ON productos (descripcion_5)');
        $this->addSql('CREATE UNIQUE INDEX descripcion_6 ON productos (descripcion_6)');
        $this->addSql('DROP INDEX provincia ON provincias');
        $this->addSql('ALTER TABLE provincias ADD provincia_2 VARCHAR(30) DEFAULT NULL, ADD provincia_3 VARCHAR(30) DEFAULT NULL, ADD provincia_4 VARCHAR(30) DEFAULT NULL, ADD provincia_5 VARCHAR(30) DEFAULT NULL, ADD provincia_6 VARCHAR(30) DEFAULT NULL, CHANGE provincia provincia_1 VARCHAR(50) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX provincia_1 ON provincias (provincia_1)');
        $this->addSql('CREATE UNIQUE INDEX provincia_2 ON provincias (provincia_2)');
        $this->addSql('CREATE UNIQUE INDEX provincia_3 ON provincias (provincia_3)');
        $this->addSql('CREATE UNIQUE INDEX provincia_4 ON provincias (provincia_4)');
        $this->addSql('CREATE UNIQUE INDEX provincia_5 ON provincias (provincia_5)');
        $this->addSql('CREATE UNIQUE INDEX provincia_6 ON provincias (provincia_6)');
        $this->addSql('DROP INDEX servicio ON servicios');
        $this->addSql('ALTER TABLE servicios ADD servicio_2 VARCHAR(50) DEFAULT NULL, ADD servicio_3 VARCHAR(50) DEFAULT NULL, ADD servicio_4 VARCHAR(50) DEFAULT NULL, ADD servicio_5 VARCHAR(50) DEFAULT NULL, ADD servicio_6 VARCHAR(50) DEFAULT NULL, CHANGE servicio servicio_1 VARCHAR(50) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX servicio_1 ON servicios (servicio_1)');
        $this->addSql('CREATE UNIQUE INDEX servicio_2 ON servicios (servicio_2)');
        $this->addSql('CREATE UNIQUE INDEX servicio_3 ON servicios (servicio_3)');
        $this->addSql('CREATE UNIQUE INDEX servicio_4 ON servicios (servicio_4)');
        $this->addSql('CREATE UNIQUE INDEX servicio_5 ON servicios (servicio_5)');
        $this->addSql('CREATE UNIQUE INDEX servicio_6 ON servicios (servicio_6)');
        $this->addSql('DROP INDEX tipaccion ON tipacciones');
        $this->addSql('ALTER TABLE tipacciones ADD tipaccion_2 VARCHAR(20) DEFAULT NULL, ADD tipaccion_3 VARCHAR(20) DEFAULT NULL, ADD tipaccion_4 VARCHAR(20) DEFAULT NULL, ADD tipaccion_5 VARCHAR(20) DEFAULT NULL, ADD tipaccion_6 VARCHAR(20) DEFAULT NULL, CHANGE tipaccion tipaccion_1 VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX tipaccion_1 ON tipacciones (tipaccion_1)');
        $this->addSql('CREATE UNIQUE INDEX tipaccion_2 ON tipacciones (tipaccion_2)');
        $this->addSql('CREATE UNIQUE INDEX tipaccion_3 ON tipacciones (tipaccion_3)');
        $this->addSql('CREATE UNIQUE INDEX tipaccion_4 ON tipacciones (tipaccion_4)');
        $this->addSql('CREATE UNIQUE INDEX tipaccion_5 ON tipacciones (tipaccion_5)');
        $this->addSql('CREATE UNIQUE INDEX tipaccion_6 ON tipacciones (tipaccion_6)');
        $this->addSql('DROP INDEX tipcliente ON tipclientes');
        $this->addSql('ALTER TABLE tipclientes ADD tipcliente_2 VARCHAR(20) DEFAULT NULL, ADD tipcliente_3 VARCHAR(20) DEFAULT NULL, ADD tipcliente_4 VARCHAR(20) DEFAULT NULL, ADD tipcliente_5 VARCHAR(20) DEFAULT NULL, ADD tipcliente_6 VARCHAR(20) DEFAULT NULL, CHANGE tipcliente tipcliente_1 VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX tipcliente_2 ON tipclientes (tipcliente_2)');
        $this->addSql('CREATE UNIQUE INDEX tipcliente_3 ON tipclientes (tipcliente_3)');
        $this->addSql('CREATE UNIQUE INDEX tipcliente_4 ON tipclientes (tipcliente_4)');
        $this->addSql('CREATE UNIQUE INDEX tipcliente_5 ON tipclientes (tipcliente_5)');
        $this->addSql('CREATE UNIQUE INDEX tipcliente_6 ON tipclientes (tipcliente_6)');
        $this->addSql('DROP INDEX tipcombustible ON tipcombustibles');
        $this->addSql('ALTER TABLE tipcombustibles ADD tipcombustible_2 VARCHAR(20) DEFAULT NULL, ADD tipcombustible_3 VARCHAR(20) DEFAULT NULL, ADD tipcombustible_4 VARCHAR(20) DEFAULT NULL, ADD tipcombustible_5 VARCHAR(20) DEFAULT NULL, ADD tipcombustible_6 VARCHAR(20) DEFAULT NULL, CHANGE tipcombustible tipcombustible_1 VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX tipcombustible_1 ON tipcombustibles (tipcombustible_1)');
        $this->addSql('CREATE UNIQUE INDEX tipcombustible_2 ON tipcombustibles (tipcombustible_2)');
        $this->addSql('CREATE UNIQUE INDEX tipcombustible_3 ON tipcombustibles (tipcombustible_3)');
        $this->addSql('CREATE UNIQUE INDEX tipcombustible_4 ON tipcombustibles (tipcombustible_4)');
        $this->addSql('CREATE UNIQUE INDEX tipcombustible_5 ON tipcombustibles (tipcombustible_5)');
        $this->addSql('CREATE UNIQUE INDEX tipcombustible_6 ON tipcombustibles (tipcombustible_6)');
        $this->addSql('DROP INDEX tipcontacto ON tipcontactos');
        $this->addSql('ALTER TABLE tipcontactos ADD tipcontacto_2 VARCHAR(20) DEFAULT NULL, ADD tipcontacto_3 VARCHAR(20) DEFAULT NULL, ADD tipcontacto_4 VARCHAR(20) DEFAULT NULL, ADD tipcontacto_5 VARCHAR(20) DEFAULT NULL, ADD tipcontacto_6 VARCHAR(20) DEFAULT NULL, CHANGE tipcontacto tipcontacto_1 VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX tipcontacto_1 ON tipcontactos (tipcontacto_1)');
        $this->addSql('CREATE UNIQUE INDEX tipcontacto_2 ON tipcontactos (tipcontacto_2)');
        $this->addSql('CREATE UNIQUE INDEX tipcontacto_3 ON tipcontactos (tipcontacto_3)');
        $this->addSql('CREATE UNIQUE INDEX tipcontacto_4 ON tipcontactos (tipcontacto_4)');
        $this->addSql('CREATE UNIQUE INDEX tipcontacto_5 ON tipcontactos (tipcontacto_5)');
        $this->addSql('CREATE UNIQUE INDEX tipcontacto_6 ON tipcontactos (tipcontacto_6)');
        $this->addSql('DROP INDEX tipempleado ON tipempleados');
        $this->addSql('ALTER TABLE tipempleados ADD tipempleado_2 VARCHAR(20) DEFAULT NULL, ADD tipempleado_3 VARCHAR(20) DEFAULT NULL, ADD tipempleado_4 VARCHAR(20) DEFAULT NULL, ADD tipempleado_5 VARCHAR(20) DEFAULT NULL, ADD tipempleado_6 VARCHAR(20) DEFAULT NULL, CHANGE tipempleado tipempleado_1 VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX tipempleado_1 ON tipempleados (tipempleado_1)');
        $this->addSql('CREATE UNIQUE INDEX tipempleado_2 ON tipempleados (tipempleado_2)');
        $this->addSql('CREATE UNIQUE INDEX tipempleado_3 ON tipempleados (tipempleado_3)');
        $this->addSql('CREATE UNIQUE INDEX tipempleado_4 ON tipempleados (tipempleado_4)');
        $this->addSql('CREATE UNIQUE INDEX tipempleado_5 ON tipempleados (tipempleado_5)');
        $this->addSql('CREATE UNIQUE INDEX tipempleado_6 ON tipempleados (tipempleado_6)');
        $this->addSql('DROP INDEX tipingreso ON tipingresos');
        $this->addSql('ALTER TABLE tipingresos ADD tipingreso_2 VARCHAR(20) DEFAULT NULL, ADD tipingreso_3 VARCHAR(20) DEFAULT NULL, ADD tipingreso_4 VARCHAR(20) DEFAULT NULL, ADD tipingreso_5 VARCHAR(20) DEFAULT NULL, ADD tipingreso_6 VARCHAR(20) DEFAULT NULL, CHANGE tipingreso tipingreso_1 VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX tipingreso_1 ON tipingresos (tipingreso_1)');
        $this->addSql('CREATE UNIQUE INDEX tipingreso_2 ON tipingresos (tipingreso_2)');
        $this->addSql('CREATE UNIQUE INDEX tipingreso_3 ON tipingresos (tipingreso_3)');
        $this->addSql('CREATE UNIQUE INDEX tipingreso_4 ON tipingresos (tipingreso_4)');
        $this->addSql('CREATE UNIQUE INDEX tipingreso_5 ON tipingresos (tipingreso_5)');
        $this->addSql('CREATE UNIQUE INDEX tipingreso_6 ON tipingresos (tipingreso_6)');
        $this->addSql('DROP INDEX tippago ON tippagos');
        $this->addSql('ALTER TABLE tippagos ADD tippago_2 VARCHAR(30) DEFAULT NULL, ADD tippago_3 VARCHAR(30) DEFAULT NULL, ADD tippago_4 VARCHAR(30) DEFAULT NULL, ADD tippago_5 VARCHAR(30) DEFAULT NULL, ADD tippago_6 VARCHAR(30) DEFAULT NULL, CHANGE tippago tippago_1 VARCHAR(30) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX tippago_1 ON tippagos (tippago_1)');
        $this->addSql('CREATE UNIQUE INDEX tippago_2 ON tippagos (tippago_2)');
        $this->addSql('CREATE UNIQUE INDEX tippago_3 ON tippagos (tippago_3)');
        $this->addSql('CREATE UNIQUE INDEX tippago_4 ON tippagos (tippago_4)');
        $this->addSql('CREATE UNIQUE INDEX tippago_5 ON tippagos (tippago_5)');
        $this->addSql('CREATE UNIQUE INDEX tippago_6 ON tippagos (tippago_6)');
        $this->addSql('DROP INDEX tipvehiculo ON tipvehiculos');
        $this->addSql('ALTER TABLE tipvehiculos ADD tipvehiculo_2 VARCHAR(20) DEFAULT NULL, ADD tipvehiculo_3 VARCHAR(20) DEFAULT NULL, ADD tipvehiculo_4 VARCHAR(20) DEFAULT NULL, ADD tipvehiculo_5 VARCHAR(20) DEFAULT NULL, ADD tipvehiculo_6 VARCHAR(20) DEFAULT NULL, CHANGE tipvehiculo tipvehiculo_1 VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX tipvehiculo_1 ON tipvehiculos (tipvehiculo_1)');
        $this->addSql('CREATE UNIQUE INDEX clasificacion ON tipvehiculos (clasificacion)');
        $this->addSql('CREATE UNIQUE INDEX tipvehiculo_2 ON tipvehiculos (tipvehiculo_2)');
        $this->addSql('CREATE UNIQUE INDEX tipvehiculo_3 ON tipvehiculos (tipvehiculo_3)');
        $this->addSql('CREATE UNIQUE INDEX tipvehiculo_4 ON tipvehiculos (tipvehiculo_4)');
        $this->addSql('CREATE UNIQUE INDEX tipvehiculo_5 ON tipvehiculos (tipvehiculo_5)');
        $this->addSql('CREATE UNIQUE INDEX tipvehiculo_6 ON tipvehiculos (tipvehiculo_6)');
    }
}
